### ISSUE TITLE
Goal 1 (Aug. 25): Implement a single interactable object

### ISSUE THREAD

**Issue by benjackson45** [UQdeco2800/2021-studio-7#10]
# **Description**
**Task**: Implement a single interactable object
**Feature**: Interactable Objects

Create a single interactable object which shows a simple animation when interacted with. 
The entity should only be able to be interacted with once the player is in contact with it, and once interacted with (via the 'e' key), the entity should display a small animation or change the sprite that it is showing.
 
# **Milestones**
- [x] Goal 1 (Aug 23): Implement an InteractableComponent class for the interactable entity to inherit, and should be able to check for a collision with the player.
- [x] Goal 2 (Aug. 24): Setup a key for the player to press in order to 'interact' with the interactable entity.
- [x] Goal 3 (Aug. 31): Display an animation once the entity has been interacted with.
 
**Completion Deadline:** Aug 25th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/Object-Interaction)
 
# **Members**
- Treffery (@tweeeb )
- Ben (@benjackson45 )
- Jiarui (@Jrui24 )
- Junxiang (@Noctisw )
- Pranay (@pranaypremdas )
