### ISSUE TITLE
Implement Task System

### ISSUE THREAD

**Issue by benjackson45** [UQdeco2800/2021-studio-7#100]
# **Description**
**Task:** Implement Task System
 
Create a task system within the game that gives the player a list of tasks to complete before getting to bed. 

# **Milestones**
- [ ] Implement a TaskController class
- [ ] Implement a TaskList UI to list tasks to complete
- [ ] Create several basic tasks for the player to complete
 
**Completion Deadline:** Oct. 7
 
# **Documentation**
 TODO

# **Member**
- Ben Jackson (@benjackson45)
- Pranay Premdas (@pranaypremdas )
- Treffery Webb (@tweeeb)
