### ISSUE TITLE
Random Map Generation with Prefabs

### ISSUE THREAD

**Issue by Jantoom** [UQdeco2800/2021-studio-7#102]
## Description
This feature extends upon the room generation concept in Sprint 2. The aim is to abstract generation enough so that random parameters can be added to simulate random home generation. 

Prefabricated rooms and floor plans will be used to construct a floor. They will be in JSON format using custom object deserialization. This should allow other studio members to easily make their own rooms and floor plans.

A side effect is that entity factories will be cleaned up to limit duplicate lines of code, and streamline dependency injection from JSON file to object creation.

## Dependencies
None

## Documentation
[Random Map Generation System](https://github.com/UQdeco2800/2021-studio-7/wiki/Random-Map-Generation-System)

## Milestones
- [x] Create conceptual diagram for home abstraction
- [x] Create relevant classes
- [x] Transition from DRM to JSON serialization, finalize contents
- [x] Write mock files for full home generation
- [x] Extend file loading and reading capabilities
- [x] Implement random selection of floor plans and room interiors
- [x] Refactor entity factories to accommodate serialized generation
- [x] Re-implement tile and entity generation
- [x] Write new random generation documentation
- [x] Extend prefab database to simulate randomness

## Members
- Jaleel Abdur-Raheem (@Jantoom)
- Ethan Roderick (@E-Roderick)

**Comment by Jantoom** [comment]
@uqnjain @naziah28
