### ISSUE TITLE
Isometric Collision and Hitbox Shapes (Team 3)

### ISSUE THREAD

**Issue by E-Roderick** [UQdeco2800/2021-studio-7#103]
## Description

**Task**: Isometric Collision and Boundary Boxes

Fixing of the orthogonal grid collision and boundary boxes. This is post-completion documentation of the task.

At sprint start, collision and boundary boxes were based on the orthogonal grid, rather than isometric. The first step to temporarily resolve was rotation of these square boxes, however this implementation had misaligned overlap (as the pieces were placed on an isometric grid). 

The next iteration involved using tangent and the isometric angles to calculate vector points for an isometric grid. This was misaligned by just a few pixels around corners.

Finally, as the game engine emulates an isometric view using a 1:2 ratio, this was used to calculate near perfect isometric vector positions.

## Dependencies
None.

## Milestones

- [x] Get isometric vector points
- [x] Implement isometric boxes
- [x] Proper implementation of isometric collision and hitbox bounds (centred)

## Members
- @E-Roderick

**Comment by s4594749** [comment]
![](https://raw.githubusercontent.com/UQdeco2800/2021-studio-7/main/source/core/assets/images/objects/furniture/Bookcase.png)

**Comment by s4594749** [comment]
![](https://raw.githubusercontent.com/UQdeco2800/2021-studio-7/main/source/core/assets/images/objects/furniture/Lounge.png)

**Comment by s4594749** [comment]
![](https://github.com/UQdeco2800/2021-studio-7/blob/main/source/core/assets/images/objects/furniture/diningtable.png)

**Comment by E-Roderick** [comment]
@s4594749 I think this was commented on the wrong ticket

**Comment by s4594749** [comment]
ohhhh shit

**Comment by s4594749** [comment]
> @s4594749 I think this was commented on the wrong ticket

sorry dude

**Comment by E-Roderick** [comment]
This task has been carried over into Sprint 4
