### ISSUE TITLE
Generating Room Objects from a .drm File (Team 3)

### ISSUE THREAD

**Issue by E-Roderick** [UQdeco2800/2021-studio-7#11]
## Description

**Task**: Generating Room Objects from a .drm File

**Feature**: [Map Design with Map Objects](#6)

Implement a `RoomLoader` class that can take `drm` files and convert their contents into a usable `MapRoom` object. The `RoomLoader` will handle the file using the [specified syntax](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Generation#drm-files), stripping white text and comments and performing some rudimentary error case handling. The parsed lines for the `drm` files will then be used to create the information needed to construct a `MapRoom` object. This will be repeatable for all of the `drm` files in a given folder, giving an `ArrayList` of `MapRoom` objects.

## Dependencies

None.

## Milestones

- [x] Loading and parsing of all `drm` file contents.
- [x] `MapRoom` object creation with file info.
- [x] Implement function to load all `drm` files in a given directory.

## Documentation

- [Map Generation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Generation)

## Members

- Ethan Roderick (@E-Roderick)
