### ISSUE TITLE
Modify and create UML Diagrams, fix bugs and create new entity

### ISSUE THREAD

**Issue by wenqi6** [UQdeco2800/2021-studio-7#112]
**Task:**Combine the class diagrams into one and create class diagrams and sequence diagrams for the new classes. Fix bugs in the Sonar Cloud，create wiki page for them and also create cat entity.

# **Milestones**
- [x] combine the class diagrams (Oct. 5)
- [x] create new class diagrams and sequence diagramsr(Oct. 5)
- [x] fix bugs(Oct. )5
- [x] create wiki page(Oct. 5)
- [x] create cat entity (Oct, 5)
