### ISSUE TITLE
Improving and Fully Implementing Pause Screen

### ISSUE THREAD

**Issue by rbrowning66** [UQdeco2800/2021-studio-7#113]
# **Description**
Task : Improve pause screen and polish functionality.

# **Milestones**
- [x] Pausing all entities in game (September 26)
- [x] Displaying pause menu (September 28)
- [x] Resuming all entities in game, saving state (Oct 3)
- [x] Removing pause menu when resuming (Oct 4)
- [x] Polishing (Oct 6) 

Completion Deadline: Oct. 6

# **Members**
Roy Browning (@rbrowning66) (Roy Browning)
