### ISSUE TITLE
Generating a Game Area from a Collection of Rooms (Team 3)

### ISSUE THREAD

**Issue by E-Roderick** [UQdeco2800/2021-studio-7#12]
## Description

**Task**: Generating a Game Area from a Collection of Rooms

**Feature**: [Map Design with Map Objects](#6)

Implement a `MapController` that, if provided with a collection of `MapRoom` objects can convert the contained information into a usable tile map and `GameArea`. The tile map will be constructed by a terrain factory and consist of the amalgamation of tiled areas from the `MapRoom` objects, and inform a terrain component. This terrain component will then be used to generate a game level.

## Dependencies

- [Generating Room Objects from a .drm File](#11).
- Isometric view/camera.

## Milestones

- [x] Parsing of a collection of `MapRoom` objects.
- [x] Implementation of custom `TerrainFactory` behaviour to generate maps.
- [ ] Implementation of custom `GameArea` that uses the custom map generation.

## Documentation

- [Map Generation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Generation)

## Members

- Ethan Roderick (@E-Roderick)

**Comment by E-Roderick** [comment]
Completed implementation of first two milestones. Will continue work on milestone 3 after confirming details regarding isometric camera view (#8).
