### ISSUE TITLE
Pause and Timer Displays V2

### ISSUE THREAD

**Issue by Jantoom** [UQdeco2800/2021-studio-7#125]
## Description
**Task**: Fix pause and timer display implementations
**Feature**: [Team 5](https://github.com/UQdeco2800/2021-studio-7/issues/138)

General code refactoring of pause and timer displays. Pausing is currently all over the place and not using proper composition. Timer code is quite bloated. Small improvements to be added along the way.

## Dependencies
None.

## Milestones
- [ ] User testing for opaque vs transparent background, button placement/usage, keyboard allocation and functionality
- [x] Remove excess code from `MainGameScreen`
- [x] Compartmentalize all functionality into a `UIComponent`
- [x] Complete pause functionality
- [ ] Additional pause improvements
- [x] Simplify code from `MainGameTimerDisplay`
- [x] Center timer label on the display
- [x] Add queueing system for switching screens to eliminate bad update/render calls
- [ ] Fix any remaining sonarcloud bugs

## Documentation
None.

## Members
Jaleel Abdur-Raheem @Jantoom
