### ISSUE TITLE
Improvement and fixes for minimap, main menu scroll and context screen (Team 4)

### ISSUE THREAD

**Issue by AnsonCNS** [UQdeco2800/2021-studio-7#126]
## Description
This feature ticket will be focused on improving and bug fixing some of our existing features implemented in Sprint 3 #88, which includes the Minimap, Menu Scroll, and Context Screen. 

The minimap will need to be further worked on to ensure that it is positioned at the bottom left corner, instead of at the player. We also need to work on loading walls and game assets into the Minimap, without affecting the asset loading of the main game. Depending on user testings, a frame might be added to differentiate the minimap from the main game area.

The main menu scrolling needs to be fixed such that the frame surrounding the selected buttons will transform proportionally when in full screen mode. This keyboard selection/scrolling feature will be adopted in other menu screens such as the Pause menu.

Further work in the context screen are required to provide a more appropriate overview of the game to players.

## Dependencies
Team 3 for the mini map generation 

## Documentation
* [Minimap](https://github.com/UQdeco2800/2021-studio-7/wiki/Minimap)
* [Keyboard Functionality for Main Menu](https://github.com/UQdeco2800/2021-studio-7/wiki/Keyboard-Functionality-for-Main-Menu)

## Milestones
- [ ] Modify context screen information
- [ ] Full screen main menu scroll select
- [ ] Scroll select for other screens
- [ ] Minimap positioning
- [ ] Minimap load assets

## Members
* Nok Sang Chan (@AnsonCNS)
* Michelle Kwok (@MishKwok )
* Hayden Padget (@44818919 )
* Krisna Bou (@MrMeatballs )
* Yue Zhang (@yuezhang7 )
