### ISSUE TITLE
Game polishing and bug fixing (Team 3)

### ISSUE THREAD

**Issue by Luke-Cronin** [UQdeco2800/2021-studio-7#128]
## Description

This feature involves polishing and fixing existing bugs in the game in many areas of gameplay. 

For player movement, the vectors add together when the user presses up and across so this needs to be kept consistent with the up and across movement speeds. The angle which the player moves is not in the isometric world frame and should be changed to be consistent with game tiles/world. 

For the door interaction collision component needs to be fixed as it would never allow the player to walk through it to enter house/rooms. 

Hitboxes and collisions for objects and walls are going to be standardized and fixed to represent the actual shapes of obejcts in the game. 

JUnit Test coverage needs to be expanded to encompass all code in the game

Depending on other team workload and focus, we will manage bug fixes (and other sonarcloud stuff) with other teams and assign a realistic amount of work based on their sprint difficulty.

## Dependencies

To be filled out. 

## Documentation

To be filled out. 

## Milestones

- [ ] Polish/Fix existing textures
- [ ] Fix player movement vectors
- [ ] Fix player movement direction/angle
- [ ] Fix door interaction
- [ ] Fix collisions with interactables and other objects
- [ ] Sonarcloud bug fixes
- [ ] JUnit Test coverage

## Members
- Luke Cronin (@Luke-Cronin)
- June Lee (@junelee045)
- Ethan Roderick (@E-Roderick)
- Yongzhi Zhou (@45229848)	
- Yichuan Chen (@YichuanChen)

**Comment by Luke-Cronin** [comment]
@uqnjain Team 3 has filled out our Sprint 4 Feature ticket

**Comment by junelee045** [comment]
Completed door interaction

**Comment by E-Roderick** [comment]
Removed JUnit test milestone
