### ISSUE TITLE
Player's & NPC's animations improvement, sprites refinement, testing and bug fixing (Team 1)

### ISSUE THREAD

**Issue by ChanghaoXi** [UQdeco2800/2021-studio-7#129]
# **Description**

**Task:** Improving quality and smoothness of animations for playable characters & NPCs, finishing character sprites from the previous sprint, implementing animation for in-game NPC cat, conducting user testing for character design and iterating it based on feedback gathered for one last time, finalising documentation for all related wiki pages, UML diagramming. Additionally, Team 1 will contribute to Junit testing coverage and debugging for the studio. 

**Feature:** Animation improvements, iteration of sprites design and finalisation of documentation on wiki.

In the last sprint, Team 1 will focus on finishing the tasks left from last sprint, improving the quality of work that has been done individually as a team from previous sprints, and collaboratively improving the quality of game with other teams as a whole.  More specifically, Team 1 will allocate time to finish the following tasks: 

- **Finishing sprites for characters:** Additional sprites creation left from the previous sprint for playable characters boy_00 and girl_00 will be the priority of Team 1 for this sprint. Similar to character boy_01, the set of sprites for other two playable characters will be expanded using the 3rd edition of basic character sprites as a foundation. Apart from that, several extra sprites may be added to increase the smoothness of animations. 

- **Documentation:** Documenting process and decisions and justifications regarding programming on related wiki pages will be an important part of work in the last sprint as it provides stakeholders of the game with basic understanding of game design & internal logic of animation implemented. At this stage, restructuring existing wiki pages to improve readability & reduce duplication of information; finalising new wiki pages and strengthening the connection between different wiki pages for better logical flows will be the goals of documentation for this sprint.

- **Animations:** Implement animation for in-game NPC 'cat_00' and update animations for other playable characters and NPCs to make the sprites made in the previous sprint presented in game correctly. Additionally, extra in-game action (i.e. hand waving) will be included as part of the animation implementations too. For NPC, mom_00, simple pathfinding algorithm that allows mom to chase playable character will be implemented using existing packages.

- **Implementation of 'Speed up' function:** The Speed up function will be triggered after the playable character picked a can of energy drink, the moving speed of that character will be incresed temperarily for 5 to 10 seconds, with an increase of stamina value as well. During the period of time that the character is having a speed up buff, this function will switch the sprites to the one with light blue outlines (for boy_01 & girl_00) and light green (for boy_00). After the duration of 5-10 seconds of speed up status, the speed of playable characters will back to normal, as well as colour of outlines (back to black normal outlines).

- **Return of the Mom NPC:** The Mom NPC is back to the game again, she will enter the main room and wait there for the playable character to come and started to follow them in fixed room settings, this implementation is an alternate solution to the path finding. It will also bring a bit of tension to the game.

- **Testing, debugging and UML diagramming:** Similar to the previous sprint, more Junit tests will be constructed for classes implemented by Team 1 in this sprint, as well as in previous sprints. On top of that, based on results in Sonar Cloud, Junit tests and debugging for classes written by other teams but haven't been covered will be done, to increase the general quality of the game. For user testing, as is mentioned before, in team and studio-wide user testing sessions will both be conducted. UML diagrams will also be updated based on the implementation for this sprint, as visualisation of finished work and relationship between each part of them.   

**Please check the wiki pages listed under the documentation section for more information. Thank you!**

#  **Dependencies**
- Improving character's & NPC's animation and related documentations will depend on animations implemented in previous sprint #37.
- Iterating design of characters & NPCs sprites and related documentations will depend on sprites designed and developed in previous sprint #87.

# **Tasks**
- #141 .
- #142 .
- #156 .
- #144.

# **Milestones**

- [x] Step 1 [Oct. 17]: Conducting user testing for all playable characters and NPCs. 
- [x] Step 2 [Oct. 18]: Reviewing functions implemented and debugging.
- [x] Step 3 [Oct. 18]: Completing Junit tests for all classes implemented.
- [x] Step 4 [Oct. 20]: Updating sprites for the playable character girl_00.
- [x] Step 5 [Oct. 19]: Drawing UML diagrams for classes/functions implemented and documented on wiki.
- [x] Step 6 [Oct. 20]: Implementing animation for the NPC cat_00.
- [x] Step 7 [Oct. 21]: Finishing documentation on wiki for movement animations.

- [x]  **Completion Deadline** [Oct. 21]

# **Documentation**
- [Characters & NPCs Design](../..//2021-studio-7/wiki/Character-&-NPCs-Design)
- [Characters & NPCs Design User Testing](../..//2021-studio-7/wiki/Characters-&-NPCs-Design-User-Testing)
- [Enemy Design Guide](../..//2021-studio-7/wiki/Enemy-Design-Guide)
- [Movement Animations](../..//2021-studio-7/wiki/Movement-Animations)
- [Styling Guide and Best Practices for Studio 7](../..//2021-studio-7/wiki/Styling-Guide-and-Best-Practices-for-Studio-7)
- [Character Interaction Animations](../..//2021-studio-7/wiki/Character-Interaction-Animations)

# **Members**
**Benjamin Israel** (@benisrael29) (Benjamin Israel)
**Changhao Xi** (@ChanghaoXi) (Raymond)
**Tina Goyal** (@tinagoyal203) (Tina Goyal)
**Wenqi Lyu** (@wenqi6) (Wenqi Lyu)
**Yiling Shi** (@shiyiling1) (Jessie)
