### ISSUE TITLE
Communication between Physics Collisions and Player Entity

### ISSUE THREAD

**Issue by tweeeb** [UQdeco2800/2021-studio-7#13]
# **Description**
**Task**: Implement a method of communication from the PhysicsContactListener to the player, so they player entity knows what intractable components it is touching, and can potentially interact with.
**Feature**: Interactable Objects

The PhysicsContactListner class listens to all global collisions occurring and will check if a collision is occurring with a target Fixture (class implemented by ColliderComponent which is analogous to a rectangle to which the entities physics is applied). The target fixture will be the one attributed to the Players ColliderComponent.  When a player Fixture collision occurs, PhysicsContactListener will communicate with the Player characters component PlayerObjectInteractions to check if the other entity participating in the collision is a Interactable object (#10) and then add the object to an ArrayList in the PlayerObjectInteractions component if it is. When the collision ends the object will then be removed from that list.

This function is important so the Player knows what entities it is touching, so when the Player attempts to interact, the interaction function will be called on the correct entity from the human readable game. Some of these interactions will change the stats of the player character (stamina), the game mode (win or lose), or the game map (moving furniture and fixtures).
 
# **Milestones**
- [x]  Parse targetFixture into PhysicsComponentListener
- [x]  PhysicsComponentListener can detect collisions involving the targetFixture
- [x]  PlayerObjectInteractions component created
- [x] Physics CompoenentListener parses information pertaining to targetFixture to PlayerObjectInteractions
- [x] PlayerObjectInteractions only stores entities that have the InteractableComponent.
- [x] When the collision ends, the entity the Player was previously touching is removed from PlayerObjectInteractions
 
**Completion Deadline:** Aug 31th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/Object-Interaction)
 
# **Members**
- Treffery (@tweeeb )
- Ben (@benjackson45 )
- Pranay (@pranaypremdas )
