### ISSUE TITLE
Random Map Generation V2.1

### ISSUE THREAD

**Issue by Jantoom** [UQdeco2800/2021-studio-7#131]
## Description
**Feature:** [Team 5 Sprint 4](https://github.com/UQdeco2800/2021-studio-7/issues/138)

Few more changes and additions to the underlying map generation. Most of these will be focused on ease-of-use for other studio members, documentation, code coverage and bug fixes.

## Dependencies
None.

## Documentation
[Random Map Generation System](https://github.com/UQdeco2800/2021-studio-7/wiki/Random-Map-Generation-System)

## Milestones
- [ ] User testing for room and home sizes
- [x] Enforce hard map borders so players cannot escape the world
- [x] Enforce bed spawning so only one bed per floor belongs to the player
- [x] Enforce accessible doorways by choosing interior orientations that don't block doorways
- [x] Implement dynamic player spawning area
- [x] Unit testing for maps and utils packages
- [ ] Sonarcloud bug fixes in maps and utils packages
- [ ] Finalise UML Class Diagram
- [ ] Create UML Sequence Diagram
- [x] Categorise all Map Generation wiki pages into the Table of Contents

## Members
Jaleel Abdur-Raheem (@Jantoom)

**Comment by uqnjain** [comment]
Looking good!
