### ISSUE TITLE
Interaction Superclass V3.1 and Component Superclass Improvements

### ISSUE THREAD

**Issue by Jantoom** [UQdeco2800/2021-studio-7#134]
## Description
**Feature:** [Team 5 Sprint 4](https://github.com/UQdeco2800/2021-studio-7/issues/138)

Few more changes and additions to the underlying interaction superclass and related classes. Most of these will be focused on ease-of-use for other studio members, documentation, code coverage and bug fixes.

## Dependencies
None.

## Documentation
[Interaction System](https://github.com/UQdeco2800/2021-studio-7/wiki/Interaction-System)

## Milestones
- [ ] User testing for singular vs. multiple highlighting, collision and interaction range
- [x] Refactor usage of manipulating entity animation
- [x] Implement component creation priority to alleviate component and event listener dependencies
- [x] Unit testing for interactions package
- [x] Logger bug fixes from asset errors
- [ ] Sonarcloud bug fixes in component-related packages
- [ ] Finalise UML Class Diagram
- [ ] Create UML Sequence Diagram
- [ ] Categorise all Interaction wiki pages into the Table of Contents

## Members
Jaleel Abdur-Raheem (@Jantoom)
