### ISSUE TITLE
Improving timer, adding designs, improving map generation and improving sonar cloud ratings (Team 5)

### ISSUE THREAD

**Issue by rbrowning66** [UQdeco2800/2021-studio-7#138]
## Description
The team is working separately in the final sprint. Each team member is working on different parts of the game or assisting other teams as the game loop in its simplest form is fully functional.

## Dependencies
N/A

## Documentation
[Random Map Generation System](https://github.com/UQdeco2800/2021-studio-7/wiki/Random-Map-Generation-System)

## Milestones
- [x] Finish up timer and polish it to user testing recommendations
- [x] Add unit testing for timer
- [ ] Improvements to pause screen display
- [x] Improvements to random map generation
- [ ] Improvements to Interaction and general Component Superclasses
- [x] Improve sonar cloud ratings i.e. removing bugs and reducing code smells

## Members
Jaleel Abdur-Raheem (@Jantoom)
Roy Browning (@rbrowning66)
Hao Liang (@s4594749) (Hao Liang)
Xue Huang (@XUEHUANG521) (Xue huang)
