### ISSUE TITLE
Create Objects for Chore System

### ISSUE THREAD

**Issue by Jrui24** [UQdeco2800/2021-studio-7#140]
# **Description**
**Task:** Create more objects for chores listed to be completed.
 
# **Milestones**
- [ ] Designing books to pick up by the player
- [ ] Designing different types of trash to pick up
- [ ] A laundry system
- [ ] A dishwashing system
- [ ] A plant watering system

# **Documentation**
[Chores List UI](https://github.com/UQdeco2800/2021-studio-7/wiki/Chores-List-UI)

# **Members**
- Jiarui Li (@Jrui24 )
- Junxiang Wang (@Noctisw)

**Comment by s4594749** [comment]
![4081634724768_ pic](https://user-images.githubusercontent.com/88121884/138074584-f6df333e-c2aa-4408-8527-ed9f293af4e9.jpg)

![4111634724771_ pic](https://user-images.githubusercontent.com/88121884/138074616-44765b21-600a-495c-9178-3ea4c9bb5503.jpg)

![4131634724773_ pic](https://user-images.githubusercontent.com/88121884/138074633-9cfb8a35-1e69-469b-8efb-cc6d830364e6.jpg)
![4121634724772_ pic](https://user-images.githubusercontent.com/88121884/138074627-3a926bcb-70ec-4b78-9139-50f6adc25b72.jpg)
![4141634724800_ pic](https://user-images.githubusercontent.com/88121884/138074669-1dab6a1b-5f8e-45f6-8338-e518e9f6ae81.jpg)
finish the plant for our backyard
and upload to object files named backyard

**Comment by ChanghaoXi** [comment]
@Noctisw. Hi, this is designer from team 1, we have conducted serveral user testing sessions using the standardised user testing protocol from previous sprint, the outcome was pretty positive, and has been recorded in the wiki page 'Characters & NPCs Design User Testing Plan' https://github.com/UQdeco2800/2021-studio-7/wiki/Characters-&-NPCs-Design-User-Testing. Please have a look if you wish to.

**Comment by Jrui24** [comment]
> @Noctisw. Hi, this is designer from team 1, we have conducted serveral user testing sessions using the standardised user testing protocol from previous sprint, the outcome was pretty positive, and has been recorded in the wiki page 'Characters & NPCs Design User Testing Plan' https://github.com/UQdeco2800/2021-studio-7/wiki/Characters-&-NPCs-Design-User-Testing. Please have a look if you wish to.

Hi Raymond, thanks for letting us know, glad to hear that positive feedback received! We'll take a look later.
