### ISSUE TITLE
Super UI patching team

### ISSUE THREAD

**Issue by benjackson45** [UQdeco2800/2021-studio-7#145]
# **Description**
**Task**: Reorganise the UI

Go through all of the game screens and edit the UI in order to make the game feel consistent and fitting the theme. 
Note: feel free to add more members

# **Milestones**
- [x] Update the menu screen
- [x] Update the context screen
- [x] Update the leaderboard
- [x] Update the main game screen UI
- [x] Update the pause screen
- [x] Update the win/ lose screens

**Completion Deadline:** October 19th
 
# **Members**
- Ben (@benjackson45 )
- Mish (@MishKwok )
- Luke (@Luke-Cronin )
- Treff (@tweeeb )

**Comment by tweeeb** [comment]
Completed :)
