### ISSUE TITLE
Creating Win and Lose Screens (Team 5)

### ISSUE THREAD

**Issue by rbrowning66** [UQdeco2800/2021-studio-7#15]
## Description
**Task**: Creating Win and Lose Screen
**Feature**: #7 

Initialise win and lose screens that can be accessed by the `GdxGame` and displayed on win/loss conditions with customisable backgrounds that can be updated easily by designers on design iterations.  Theses screens will be added upon the `MainMenuScreen`, `SettingsScreen` and `MainGameScreen`. Thus, also being as easy to display.

## Dependencies
- Win and Loss conditions in gameplay, i.e. health and timer
- #5 

## Milestones
- [x] Initialise `WinScreen` class.
- [x] Initialise `LoseScreen` class.
- [x] Make compatible to `GdxGame`.

## Documentation
[Game Transition Loop](https://github.com/UQdeco2800/2021-studio-7/wiki/Game-Transition-Loop)

## Members
- Roy Browning (@rbrowning66 )
