### ISSUE TITLE
Junit test and UML diagrams

### ISSUE THREAD

**Issue by wenqi6** [UQdeco2800/2021-studio-7#156]
**Task:** Create Junit test for CatActions function. Fixed bugs in sonar cloud. Draw class diagram and sequence diagram for floor, NPCFactory and CatActions.

# **Milestones**
- [x] Fixed bugs in sonar cloud (Oct. 18)
- [x] Draw sequence diagram (Oct. 19)
- [x] Draw class diagram (Oct. 19)
- [x] Draw sequence diagram (Oct. 19)

# **Dependencies**
- #37 
- #21 

# **Documentation**
- [NPCs & Characters Design](../..//2021-studio-7/wiki/NPCs-&-Characters-Design)
