### ISSUE TITLE
Create Events for Win/Lose Handling (Team 5)

### ISSUE THREAD

**Issue by Jantoom** [UQdeco2800/2021-studio-7#18]
# Description
**Task**: Creating events in `MainGameActions` that listen for win/lose conditions, utilising events
**Feature**: MainGame/Win/Lose Transitions for the Game Loop #7

Implement three new event listeners for handling the default win condition, and "lost to time" & "caught by enemy NPC" lose conditions. These event listeners must observe event triggers from any instance within the game. Once observed, new methods in `MainGameActions` must be called to act on them. 

# Dependencies
Creating Win and Lose Screens #15

# Milestones
- [x] Add new event listeners to `MainGameActions`
- [x] Implement methods called once a win/loss event has been observed
- [x] Link methods to the setting of `EndGameScreen`

# Documentation
[Game Transition Loop](https://github.com/UQdeco2800/2021-studio-7/wiki/Game-Transition-Loop)

# Members
- Jaleel Abdur-Raheem (@Jantoom)
