### ISSUE TITLE
Design and Creation of the Basic Set of Sprites (Team 1)

### ISSUE THREAD

**Issue by ChanghaoXi** [UQdeco2800/2021-studio-7#21]
# **Description**
**Task:** Design a set of guidelines for sprites creation and create a set of basic character sprites as a foundation of future characters & NPCs creation to prevent potential inconsistency issues.
**Feature:** Character Design

To maintain the consistency of design work across multiple designers within and across teams, a set of guidelines will be designed and visualised to help future sprites creation, guidelines will be documented on the wiki page 'NPCs and Character Design' for peer review and future reference. On top of that, a set of basic character sprites are made to set up a basic frame of character design. This set of sprites are 'flat', with no shades and highlights but it can settle the size and basic settings for characters and NPCs, which can be used as a basis of sprites for each individual character and NPC to improve the efficiency of work and prevent any potential inconsistencies in advance.

As a result, a set of reusable basic sprites will be created for future character design.

**Please check the wiki page 'NPCs & character design' under the documentation section for more details, thank you!**

# **Milestones**
- [x] Make a set of design guidelines for sprites creation (Aug. 26)
- [x] Design & create a set of 12 basic character sprites (Aug. 28)
- [x] Justify and document decisions made on the wiki page 'NPCs & Character Design' (Aug. 28)

- [x] **Completion Deadline:** Aug. 28

# **Dependencies**
- #4

# **Documentation**
- [NPCs & Character Design](../..//2021-studio-7/wiki/NPCs-&-Character-Design)

# **Members**
**Changhao Xi** (@ChanghaoXi) (Raymond)

**Comment by ChanghaoXi** [comment]
Task ticket finalised and closed by @ChanghaoXi

**Comment by ChanghaoXi** [comment]
Upload related images for the 'NPCs & Characters Design' wiki page
![Sprites Design](https://user-images.githubusercontent.com/88121807/131663133-dd8a07f0-b19c-47d9-91ce-fb6b0f81f731.png)
![Basic Sprites Final Version](https://user-images.githubusercontent.com/88121807/131663154-3b812a36-dcb2-4d54-bcd0-2f5384b41d43.png)
