### ISSUE TITLE
Map Design Tile/Textures Testing and Implementation (Team 3)

### ISSUE THREAD

**Issue by Luke-Cronin** [UQdeco2800/2021-studio-7#22]
## Description
**Task**: Design and Implement Wall and Floor textures to populate the world/level map to orient and assist the player with navigation within level. The floor textures are replacing the iso-grass tile/textures from the base game. The wall textures will create a border for the floor textures to represent the walls of each 'room' in the house or game level. There are several slight variation textures made for both the walls and floor main tile/textures (e.g. the wall one will have slight colour differences, the floor tile will have holes in the floorboards)

**Feature**: Map Design (Team 3)

## Milestones
- [x] Orthogonal Wall Texture
- [x] Alternate Orthogonal Wall Texture
- [x] Translate Wall Textures into Isometric tiles
- [x] Orthogonal Floor Texture
- [x] Alternate Orthogonal Floor Texture
- [x] Translate Floor Textures into Isometric tiles

## Members
- Luke Cronin (@Luke-Cronin )
