### ISSUE TITLE
Design and Creation of the Sprites for the Male Playable Character (Team 1)

### ISSUE THREAD

**Issue by ChanghaoXi** [UQdeco2800/2021-studio-7#26]
# **Description**
**Task:** Design and create a set of sprites for the male playable character and import them into the Retroactive game engine 
**Feature:** Character Design

Follow the principles in the "Game Style" wiki page and design guidelines for sprites creation, design and create sprites for the male playable character for the Retroactive game on the basis of basic character sprites created previously. Make decisions regarding characteristics such as hairstyle/hair colour; skin tone; eye colour; outfit style and colour scheme. Add on shades and highlights to the sprites to make them less flat. Justify and document all decisions and outcomes on the wiki page 'NPCs & Character Design'. Lastly, a backup copy of sprites created will be imported into the game engine and be sent to other team members who are responsible for making altars and implement associated functions.

As a result, the original image of the playable character in the game engine will be replaced by a brand new male character who fits the chosen style of Retrowave. If the player chooses to play as the male character, it will be displayed on the screen. 

**Please check the wiki page 'NPCs & character design' under the documentation section for more details, thank you!**

# **Milestones**
- [x] Design & create a set of 12 sprites for the male playable character (Aug. 28)
- [x] Add shades and highlights to the sprites of the male playable character (Aug. 30)
- [x] Justify and document decisions made on the wiki page 'NPCs & Character Design' (Sept. 01)

- [x] **Completion Deadline:** Sept. 01

# **Dependencies**
- #4 
- #21.

# **Documentation**
- [NPCs & Character Design](../..//2021-studio-7/wiki/NPCs-&-Character-Design)

# **Members**
**Changhao Xi** (@ChanghaoXi) (Raymond)

**Comment by ChanghaoXi** [comment]
Task ticket finalised and closed by @ChanghaoXi

**Comment by ChanghaoXi** [comment]
Task tick finalised and closed by @ChanghaoXi

**Comment by ChanghaoXi** [comment]
Upload related images for the 'NPCs & Characters Design' wiki page
![Male Character v1 0](https://user-images.githubusercontent.com/88121807/131662797-56b5f0ed-c775-46e9-96bc-d78e98ae07f6.png)
![Male Character WIP](https://user-images.githubusercontent.com/88121807/131662810-af4e8386-84e7-4f70-a423-64af779471b3.png)
![Male Character Demo Final Version](https://user-images.githubusercontent.com/88121807/131662824-09780076-448b-4053-9377-5d2c5cd61c74.png)
