### ISSUE TITLE
 Create sprites for the female playable character and document on wiki.

### ISSUE THREAD

**Issue by tinagoyal203** [UQdeco2800/2021-studio-7#28]
### Description
**Task**: Design and create a set of sprites for the female and the mom playable character and import them into the Retroactive game engine
**Feature**: Character Design

Follow the principles in the "Game Style" wiki page and design guidelines for sprites creation, design and create sprites for the female and the mom playable character for the Retroactive game on the basis of basic character sprites created previously. Make decisions regarding characteristics such as hairstyle/hair colour; skin tone; eye colour; outfit style and colour scheme. Justify and document all decisions and outcomes on the wiki page 'NPCs & Character Design'. Lastly, a backup copy of sprites created will be imported into the game engine and be sent to other team members who are responsible for making altars and implement associated functions.

As a result, the original image of the playable character in the game engine will be replaced by a brand new female character and the mom character who fits the chosen style of Retrowave. If the player chooses to play as the female character, it will be displayed on the screen.

Please check the wiki page 'NPCs & character design' under the documentation section for more details, thank you!

# **Milestones**
- [x] Design & create a set of 12 sprites for the female playable character (Aug. 28)
- [x]  Design & create a set of 12 sprites for the mom playable character (Aug. 28)
- [x] Add shades and highlights to the sprites of the female and mom playable character (Aug. 30)
- [x] Justify and document decisions made on the wiki page 'NPCs & Character Design' (Sept. 01)

- [x] **Completion Deadline:** Sept. 01

# **Dependencies**
- #4. 
- #21.

# **Documentation**
- [NPCs & Characters Design](../..//2021-studio-7/wiki/NPCs-&-Characters-Design)

# **Member**
**Tina Goyal** (@tinagoyal203 ) (Tina Goyal)

**Comment by tinagoyal203** [comment]
![239868814_1431509253883196_3755282941967700737_n](https://user-images.githubusercontent.com/50831109/131688412-935006da-7ead-4682-8501-050709f1d169.jpg)

**Comment by tinagoyal203** [comment]
![238310622_452230109252816_3072669085866679167_n](https://user-images.githubusercontent.com/50831109/131689156-f4c7787d-530f-40e7-a169-1690a61cc58a.jpg)

**Comment by tinagoyal203** [comment]
![234739901_315738753625577_1303138973617495333_n](https://user-images.githubusercontent.com/50831109/131689788-3d440232-efa1-4d91-9ea6-476662a4d51e.png)

**Comment by tinagoyal203** [comment]
![238472490_791920991488598_5284676825343036992_n](https://user-images.githubusercontent.com/50831109/131689925-083385e7-70e2-49b1-b256-7ed1a3b85324.jpg)
