### ISSUE TITLE
Map Generation Extended (team 3)

### ISSUE THREAD

**Issue by Luke-Cronin** [UQdeco2800/2021-studio-7#36]
## Description
This feature ticket is an extension of Sprint 1 Map Design and will lead on from Sprint 1 Feature ticket (see urls below). The wall generation was not completed in the previous ticket and will be implemented in this ticket. **(This milestone is a major priority task)**

For all textures placed, scaling and location need to be modified and adjustable. Refactor file format for the .drm files for ease of use. Once this is completed, the random map/level generation can be designed/worked on. The Random Level generation would be a good additional feature to have as it makes the game more replayable and interesting. 

Door generation and placement within the map will be implemented to create a space in the wall which players can walk through to get to adjoining rooms. Door tile/design may have to be redesigned to fit certain wall textures. 

Floor and wall texture generation will be implemented inside the .drm files. Recreating/redesigning floor and wall textures with style guild in mind and additional textures (carpet, windows, new floor tiles and new wall tiles)

[Map Design with Map Objects](https://github.com/UQdeco2800/2021-studio-7/issues/6)
[Generating a Game Area from a Collection of Rooms](https://github.com/UQdeco2800/2021-studio-7/issues/12)

## Dependencies
To be filled

## Documentation
- [Map Generation Documentation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Generation)
- [Border Generation Documentation](https://github.com/UQdeco2800/2021-studio-7/wiki/Border-Generation)

- [Map Design with Map Objects](https://github.com/UQdeco2800/2021-studio-7/issues/6)
- [Generating a Game Area from a Collection of Rooms](https://github.com/UQdeco2800/2021-studio-7/issues/12)
- [Map Floor Design Documentation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Floor-Design)

## Milestones

- [x] #39
- [x] Wall and Floor tile implementation
- [x] Finish Current Map generation (#63 )
- [ ] Random Level generation
- [x] Doors implemented (into walls)

## Members

- Luke Cronin (@Luke-Cronin)
- June Lee (@junelee045)
- Ethan Roderick (@E-Roderick)
- Yongzhi Zhou (@45229848)
- Yichuan Chen (@YichuanChen)

### What Worked

- Weekly meetings on Sunday.
- Team response times and communication.
- Good working team atmosphere.
- Good standard of produced work.

### Team Amendments

- Week's interim work updates.
  - *Rationale*: Work between each team member seemed somewhat distinct/disconnected, and with the Sunday meetings and Friday studio,  there were only updates roughly at the end of each week.
  - *Action*: Have interim updates of work done each week, ideally midway between the Sunday meeting and the following Friday studio (Wednesday). These updates will simply be a short text summary in the dedicated communication channel (following the team stand-up format: What we've done, what we will do, what is preventing work), followed by a short team meeting, if required.
- Routine merging of branch
  - *Rationale*: The merging for the end of the sprint was very stressful, and caused some issues.
  - *Action*: Routine merging of the feature branch with the main branch, to ensure branch concurrency and compatibility.
- Text and speech communication.
  - *Rationale*: Some team discussions were potentially confusing given a possible language barrier.
  - *Action*: Important ideas should be expressed in both speech and text form, allowing for post-referral and easy translation.
- Stricter deadlines for milestones and deliverables.
  - *Rationale*: The submission of sprint work was very close to the sprint's deadline, causing stress and lowering the overall amount of submitted work.
  - *Action*: Document strict but reasonable deadlines at times **before** course deadlines, to ensure completion of work. These deadlines will also need to be strictly enforced, or given a valid reason for inability to meet (along with documentation in official channels).
- Clearly defined goals and expectations.
  - *Rationale*: Weekly work was limited and obscured by unclear goals and expected, outlined work requirements.
  - *Action*: Clearly define and document the goals and deliverable required for each members' tasks. These goals could be documented within each members' respective task tickets.
- More inter-team communication.
  - *Rationale*: Work with other feature (other team) dependencies was confusing and delayed because of uncertain status of 
  - *Action*: Routine and officially documented communication with other teams regarding the status of their features, on respective ticket pages on GitHub. This communication should be used to ascertain the status of other features, as well as outlining expectations for the dependencies.

**Comment by Luke-Cronin** [comment]
@naziah28 @uqnjain Here is Team 3's feature ticket for Sprint 2

**Comment by E-Roderick** [comment]
Added Sprint One reflection details

**Comment by Jantoom** [comment]
Talked with @E-Roderick about optimising the algorithm. We agreed that I'll help him with testing in the form of mass-producing prefabs using the .drm format.

**Comment by E-Roderick** [comment]
An issue that prevented work completion for Sprint 1 - consistent file loading - has been worked on as priori to this sprint's milestones. This work was concluded by assuming that the building/running of the game was handled through Gradle, ensuring consistent results. To further practice good-coding habits, the libGDX `AssetManager` could also be extended to handling loading of `drm` file formats. This is a topic to be discussed again in a later sprint.

**Comment by 45229848** [comment]
Add a document of map floor design

**Comment by E-Roderick** [comment]
Given the scope of the map generation rework, work on the random generation of a selection of rooms is not so far completed.
