### ISSUE TITLE
Sprites creation for current characters & NPC, new character plus the scoring system implementation  (Team 1)

### ISSUE THREAD

**Issue by ChanghaoXi** [UQdeco2800/2021-studio-7#37]
# **Description**

**Task:** Add more sprites for characters & NPCs from the previous sprint from isometric views; Create sprites for a new playable character; Implement the scoring system; Implement animations for all characters covered in this sprint if possible.
**Feature:** Old Characters & NPC Update, New Character Design & the Scoring System 

In this sprint, Team 1 will be responsible for the following 3 categories of tasks:
- **Update Old Characters & NPCs:** Expanding the basic set of sprites with new isometric sprites included; redesigning sprites for characters & NPC that are created in the previous sprint based on the updated set of basic sprites; Improving the quality of sprites created in the previous sprint with shading and fixing potential issues (i.e. shapeshifting issue of the Mom NPC); Implementing animations for characters & NPCs redesigned if possible. **- This is our top priority**
- **New Character Design:** Designing and creating sprites for another male playable character based on the updated set of basic sprites with the improved standard; implementing animations for new characters & the enemy NPCs created if possible.
- **The Scoring System:** Implementing the scoring system and designing the frame & title for its in-game display.

Our team will design create or update a total number of 4 sets of sprites for in-game playable characters and NPC that are listed below
- **Male Character (boy_01):** Male version of the playable character (form sprint 1).
- **Female Character (girl_00):** Female version of the playable character (from sprint 1).
- **Mom:** An in-game NPC, which will end the game when she gets the male/female character (from sprint 1).

- **New Male Character (boy_00):** A new playable character for sprint 2, which is the second male character that can be chosen. 

Similar to the previous sprint, in order to maintain the consistency of design style across designers and teams, all sprites are created based on the studio-wide styling guidelines and updated visualised guidelines for sprites creation (the basic set of sprites). The basic set of sprites are updated and documented on the 'NPC & Character Design' wiki page. Sprites creation for all playable characters and NPCs should use the updated version of basic sprites as the foundation.

As for the implementation, classes for animations will be updated if possible, as more sprites are created for each playable character & NPC. If this cannot be achieved by the end of this sprint, it will be the priority of Team 1 for the next sprint. Additionally, classes for the in-game scoring system will also be implemented:

- Classes for implementing the in-game scoring system, which including the calculation of scores received by the player, in-game leaderboard, and display of scores received, leaderboard title & leaderboard frame.  
- Create tests for classes implemented, after classes for animations & scoring systems are done.
- If possible, update classes for implementing animations, which will switch between different sprites of the character/NPCs when they are 'walking'. This will happen when keyboard input of 'movement' command is received (for the character), or 'movement' related functions/methods of NPCs are triggered. 

**Please check the wiki pages listed under the documentation section for more information. Thank you!**
**A copy of the Sprint 2 plan for Team 1 is included down below**

#  **Dependencies**
- Updating sprites of characters & NPCs created in sprint one depends on #4 .
- Implementing all interactable components #38 

# **Tasks**
- #56 .
- #57 .
- #58 .
- #64 .
- #66 .
- #67 .
- #68 .
- #69 .
- #70 .
- #71 .

# **Milestones**

- [x] Step 1 [Sept. 10]: Make the select character button in the main menu screen functional.
- [x]  Step 2 [Sept. 12]: Expand the basic set of sprites with isometric ones, update sprites from the previous sprint and document on wiki.
- [x] #68 .
- [x] Step 4 [Sept. 13]: Redesign sprites for the male playable character based on the updated basic set of sprites and document on wiki. 
- [x] #69 .
- [x] #70 .
- [x] Step 7 [Sept. 12]: Design and create a title for in-game display of the scoring system.
- [x] Step 8 [Sept. 15]: Design and create sprites for a new male playable character based on the updated set of basic sprites and document on wiki.
- [x] Step 9 [Sept. 15]: Develop a standardised user testing plan and document on wiki.
- [x] Step 10 [Sept. 16]: Implement the scoring system.
- [x] Step 11 [Sept. 16]: Write test classes for functions implemented.

- [x]  **Completion Deadline** [Sept. 16]

# **Documentation**

- [Characters & NPCs Design User Testing](../..//2021-studio-7/wiki/Characters-&-NPCs-Design-User-Testing)
- [Movement Animations](../..//2021-studio-7/wiki/Movement-Animations)
- [NPCs & Characters Design](../..//2021-studio-7/wiki/NPCs-&-Characters-Design)
- [Scoring System and Leaderboard](../..//2021-studio-7/wiki/Scoring-System-and-Leaderboard)
- [Styling Guide and Best Practices for Studio 7](../..//2021-studio-7/wiki/Styling-Guide-and-Best-Practices-for-Studio-7)
- [UML Diagram](https://github.com/UQdeco2800/2021-studio-7/wiki/UML-Diagram)

# **Members**
**Benjamin Israel** (@benisrael29) (Benjamin Israel)
**Changhao Xi** (@ChanghaoXi) (Raymond)
**Tina Goyal** (@tinagoyal203) (Tina Goyal)
**Wenqi Lyu** (@wenqi6) (Wenqi Lyu)
**Yiling Shi** (@shiyiling1) (Jessie)

# **Sprint 2 Plan**

## **What Worked from Sprint 1**
- Weekly in-person meetings on campus or via zoom (Twice a week apart from the studio session)
- Summary notes of each meeting session for future reference by @ChanghaoXi 
- Effective communication via discord channel; Facebook Messenger channel
- General quality of output
### **More specific allocation of tasks and responsibilities**
 - **Rationale**: More specific task allocation leads to good coverage of all tasks that need to be done for the sprint and makes every team member understand what they are responsible for and working on allocated tasks.
 - **Action:** All decisions regarding task allocation will be recorded in summary notes, which will be posted in the discord channel of the team & Messenger channel. All team members will be reminded regularly of their tasks allocated and will be required for a progress check on a regular basis.
### **Detailed breakdowns for each milestone/task**
 - **Rationale:** More detailed breakdowns can make each task/milestone much easier to complete and make progress more trackable. Also, it allows individuals who are responsible for it to allocate & manage their time easier for finishing the task.
 - **Action:** All team members are required to create individual task tickets to break down their allocated tasks even further and set up deadlines for those sub-tasks and link their task ticket back to the feature tick of the team, for other team members to review. When the deadline of each sub-task has been reached, the person who is responsible for it should report back to the team about the progress made. Once a sub-task is finished, the work finished needs to be pushed to the remote feature branch.
### **Stricter deadline for tasks/milestones**
 - **Rationale:** Stricter deadlines push team members to work hard to finish allocated tasks on time and have deliverables with good quality. 
 - **Action:** Deadlines of each milestone/task are specified in the feature ticket/task ticket after all individuals within the team reached an agreement, they will not be easily changed without solid justifications & rationales, team members are required to report their progress regularly in the Messenger channel or in weekly meeting, especially when the pre-set deadlines are approaching. 
### **Slack & float time for more difficult tasks before completion of the sprint**
 - **Rationale:** The existence of slack & float time between completion of each milestone & task gives team members additional time to resolve unexpected difficulties when finishing their allocated tasks, this reduces the potential negative impacts to subsequent tasks/milestones that depend on previous ones, which will make sure that all the tasks listed in the feature ticket can be completed on time.
 - **Action:** Slack & float time will be taken into consideration when setting up deadlines for tasks/milestones and allocating tasks. Slack & float time are set with the agreement of the whole team and will be reflected in the milestone section of the feature ticket.

**Comment by ChanghaoXi** [comment]
Feature Ticket Created and Reviewed by @ChanghaoXi

**Comment by ChanghaoXi** [comment]
@naziah28 @uqnjain Hi, this is the Sprint 2 feature ticket of Team 1, please have a look, thanks :)

**Comment by ChanghaoXi** [comment]
> Please add deadlines for each milestone.

@uqnjain Deadlines for each milestone are added, please have a look, thanks :)

**Comment by ChanghaoXi** [comment]
Feature ticket reviewed and closed by @ChanghaoXi
