### ISSUE TITLE
Team 2 - Feature Ticket (Implement all Interactable Components)

### ISSUE THREAD

**Issue by pranaypremdas** [UQdeco2800/2021-studio-7#38]
# **Description**
**Task:** [Interactable Components](#2).
**Feature:** [Feature which this tasks contributes to implementing](#2)
 
This feature ticket is an extension of Sprint 1. More interactable will be implemented along with different interaction functionality. A text UI will also be implemented. 
 
# **Dependencies**
- [ ] Map implements walls (Team 5)

 
# **Milestones**
- [ ] TV and Bed Atlas's textures (Sep. 10)
- [ ] Door Interaction (Sep. 10)
- [ ] Implement Text UI (Sep. 10) 
 
**Completion Deadline:** Sep. 16
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Ben Jackson (@benjackson45)
- Jiarui Li (@Jrui24 )
- Junxiang Wang (@Noctisw)
- Pranay Premdas (@pranaypremdas )
- Treffery Webb (@tweeeb)

**Comment by uqnjain** [comment]
Could you please describe how its an extension of Sprint 1?

**Comment by ChanghaoXi** [comment]
Hello, team 2, this is Raymond from Team 1, I have finalised the new basic set of sprites with isometric ones added and old ones remade. I have posted some screenshots of the new sprites, which u can use as references to resize objects like doors in your designer's discord channel. The original size of the canvas is 64X64, and I have also marked out width and height for normal and isometric sprites. Please have a look if u have time and drop me questions if u have any, thanks :)

**Comment by ChanghaoXi** [comment]
Greetings, team 2, it's me again, I have finalised the design of the male playable character with shading, all sprites are done. I have uploaded a copy of my work to design committee & designer's channel of your team on discord, pls have look and let me know if you have any comments, thanks :)
