### ISSUE TITLE
Design Textures for NPCs and the Character (Team 1)

### ISSUE THREAD

**Issue by benisrael29** [UQdeco2800/2021-studio-7#4]
# **Description**

**Task:** Design sprites with a consistent style for the male and female playable character and the NPC 'Mom'. After all the sprites are ready, implement associated functions for altars and animations.
**Feature:** Character Design

Our team will design and create a total number of 3 sets of sprites for in-game playable characters and NPC. Including:
- **Male Character:** Male version of the playable character.
- **Female Character:** Female version of the playable character.
- **Mom:** An in-game NPC, which will end the game when she gets the male/female character.

In order to maintain the consistency of design style across designers and teams, all sprites are created based on the studio-wide game style guidelines and visualised sprite guidance. The sprite guidance is created and documented on the 'NPC & Character Design'. The visualisation of design guidance will be used to create a set of basic character sprites with the size and settings specified, which will serve as the foundation of sprites designing for each individual character. 

Apart from sprites creation, further implementations that are related to playable characters and 'Mom' will be conducted, all functions/tests implemented will be documented on the 'Movement Animations' wiki page, including:

- Classes for implementing animations, which will switch between different sprites of the character/NPCs when they are 'moving'. This will happen when keyboard input of 'movement' command is received (for the character), or 'movement' related functions/methods of NPCs are triggered. This will be achieved by collaborating with Team 4. 
- Create tests for classes implemented.

**Please check the 'NPCs & Character Design' wiki page for design-related documentation and 'Movement Animations' wiki page for implementation-related documentation. Thank you!**

#  **Dependencies**
- All dependencies already exist in 2021 DECO2800 game engine of studio 7.
- The implementation of animation classes depends on #8.

Our team will collaborate with Team 4 for the delivery of this feature 
# **Tasks**
- #21 .
- #26 .
- #27 .
- #28 .
- #29 .
- #30 .

# **Milestones**

- [x] Step 1 [Aug. 28]: Create visualised design guidelines and the basic set of sprites and document on wiki.
- [x] Step 2 [Sept. 1]: Create sprites for the male playable character and document on wiki.
- [x] Step 3 [Sept. 1]: Create sprites for the female playable character and document on wiki.
- [x] Step 4 [Sept 1] Create sprites for 'Mom' NPC and document on wiki.
- [x] Step 5 [Sept 1 ]: Implement all the sprites animations
- [x] Step 6 [Sept 1 ]: Create a character selection button on the main menu to select the character skin.

- [x]  **Completion Deadline** [Sept. 2]

# **Documentation**

- [NPCs & Characters Design](../..//2021-studio-7/wiki/NPCs-&-Characters-Design)
- [Movement Animations](../..//2021-studio-7/wiki/Movement-Animations)

# **Members**
**Benjamin Israel** (@benisrael29) (Benjamin Israel)
**Changhao Xi** (@ChanghaoXi) (Raymond)
**Tina Goyal** (@tinagoyal203) (Tina Goyal)
**Wenqi Lyu** (@wenqi6) (Wenqi Lyu)
**Yiling Shi** (@shiyiling1) (Jessie)

**Comment by uqnjain** [comment]
This is a good ticket. Could you please be specific about your "further implementations" (give us a detailed look into what you are picturing)? Additionally, dependencies include teams you might need to collaborate with to deliver your feature. Please let me know if you have questions around the same.

**Comment by ChanghaoXi** [comment]
@uqnjain 
Hello! This is Changhao from Team 1, more details regarding the implementation of classes, as well as dependencies, have been updated above, please have a look. Thank you :)

**Comment by ChanghaoXi** [comment]
Feature Ticket updated by @ChanghaoXi. With up-to-date description & milestone section, and the new 'task' session to display related task tickets.

**Comment by ChanghaoXi** [comment]
Feature Ticket Completion Confirmed by @ChanghaoXi
