### ISSUE TITLE
Team 5 - improve win/lose transitions for the Game loop

### ISSUE THREAD

**Issue by XUEHUANG521** [UQdeco2800/2021-studio-7#40]
# **Description**
Task : improve win/lose transitions and implement pause/resume transitions for the Game loop
Feature: Win/lose screen improvement, Pausing/resuming game, fix timer bug, audio design (collaborate with Team 3)  

Our issue’s main focuses in sprint 2 are improvement of win/lose transitions and implementing pause and resume game transition for the Game loop. This includes:
              - Design Pause screen and add it into the main game screen.
              - Add animation for screen transition
Display Player’s score in the main game screen and high score when the game ends.
In addition, we would collaborate with Team 3 designers to design audio for our game, this including design:
                - Menu/setting music
                - Game music
                - Win/lose jingles
                - Interaction sound effects (etc. UI, interactive entities)

#  **Dependencies**
Interactions between the player and objects that may trigger a win or lose scenario 
- Our win condition requires interaction with the bed
- Our “caught” lose condition requires interaction with the Mom NPC
- Our “time out” lose condition requires player can’t win the game until runtime per round ends
- We will collaborate with Team 1 so that player score can be implemented on time
- We will collaborate with Team 2 so that their components may trigger our dispatchers
- We will collaborate with Team 3 so that audio design can be implemented

# **Milestones**
- [x] Fix timer bug (Sept. 10)
- [ ] Implement pause screen  (Sept. 10)
- [ ] Add animation for Win/lose screen (Sept. 10)
- [ ] Display player score (Sept. 10)
Completion Deadline: Sept. 17 

# **Members**
Hao Liang (@s4594749) (Hao Liang)
Xue Huang (@XUEHUANG521) (Xue huang)
Roy Browning (@rbrowning66) (Roy Browning)
Jaleel Abdur-Raheem (@jantoom) (Jaleel Abdur-Raheem)

**Comment by YichuanChen** [comment]
I will be helping team 5 on the lose game music design
