### ISSUE TITLE
Pausing and Resuming (Team 5)

### ISSUE THREAD

**Issue by rbrowning66** [UQdeco2800/2021-studio-7#41]
## Description
**Task**: Pausing and Resuming Functionality
**Feature**: #40 

Implement pause screen to be triggered on pause, work with designers so once they complete a background it can be used. Create pause screen UI to match style of rest of the game, work with designers to match with rest of the game and any new design features they want on pause screen. Give each button functionality in game, work with studio on what buttons they want added to it. So far it will be resume, restart, main menu buttons and high-scores.

## Dependencies
- N/A

## Milestones
- [x] Create key trigger for pause screen (11/09/2021).
- [x] Implement pause screen (12/09/2021).
- [x] Create UI elements on pause screen (14/09/2021).
- [x] Add functionality to UI elements (15/09/2021).
- [x] JUnit Testing for functions added (16/09/2021).

## Documentation
[Game Transition Loop](https://github.com/UQdeco2800/2021-studio-7/wiki/Pausing-and-Resuming)

## Members
- Roy Browning (@rbrowning66 )
