### ISSUE TITLE
Context and Main Menu Screens, Stamina Bar, World Coordinate System, Box Boy Cleanup (Team 4)

### ISSUE THREAD

**Issue by AnsonCNS** [UQdeco2800/2021-studio-7#42]
## Description
This feature ticket extends various features of Sprint 1 Movement WASD and introduces new features to work on. 

The features being extended are the Stamina feature and the Isometric feature. 

A stamina bar will be implemented to represent the player stamina value. This allows players to visually see their stamina without needing to read the numbers, increasing the visual asthetics and playability of the game. The stamina bar will first be implemented using the ProgressBar class. It is aimed to use a custom designed bar later on. 

The isometric feature will be worked on by developing a world coordinate system. By Either 1. Changing the overall coordinate system to ISO parameters or 2. Creating methods to go between ISO and ORTHO dimensioning.

New features such as context and main menu screens, and Box Boy clean-up will also be worked on.

Context Screens will involve having Art/Text in screens between level/at the start of game to explain what is going on and how to play.

For the Main Menu Screen, we will work on overhauling the UI, cleaning up Box Boy components and swapping out buttons for ones more suited to the game theme. More main menu art will be designed and implemented.

Lastly, we will be removing Box Boy components that are no longer required in the game.

## Dependencies
World coordinate system depends on map designed by Team 3

## Documentation
[Player camera and Isometric](https://github.com/UQdeco2800/2021-studio-7/wiki/Player-Camera)
[Context and Main Menu Styles](https://github.com/UQdeco2800/2021-studio-7/wiki/Player-Camera)

## Milestones
- [x] Player Stamina Bar
- [x] Design Custom Player Stamina Bar
- [x] Implement Custom Player Stamina Bar
- [x] World Coordinate System
- [x] Design Art/Text for Main Menu Screen and Context Screens
- [x] Overhaul UI for Main Menu Screen
- [x] Clean up Box Boy Components

## Members
* Nok Sang Chan (@AnsonCNS)
* Michelle Kwok (@MishKwok )
* Hayden Padget (@44818919 )
* Krisna Bou (@MrMeatballs )
* Yue Zhang (@yuezhang7 )
