### ISSUE TITLE
Stamina Bar Task Ticket (Team 4)

### ISSUE THREAD

**Issue by AnsonCNS** [UQdeco2800/2021-studio-7#44]
##Description
**Task**: Stamina Bar
**Feature Ticket**: #42 

Implement stamina bar for displaying player stamina. The bar will empty and refill based on the player's current remaining stamina. In the first iteration of the Stamina Bar, the built-in LIBGDX style for ProgressBar() will be used, where the size and colour can be changed by code. After successfully implementing the default stamina bar, a custom designed bar will be implemented with the same functionality, but with aesthetics aligning the overall retro game style.

##Dependencies
- N/A

##Milestones
- [x] Create a stamina bar class for drawing the player stamina bar.
- [x] Implement the stamina bar with default Libgdx style.
- [ ] Create custom drawings and designs for the player stamina bar.
- [ ] Integrate tge custom designs to the existing stamina bar class.

##Documentation
To be filled

##Members
- Nok Sang Chan @AnsonCNS 
- Michelle Kwok @MishKwok
