### ISSUE TITLE
Main Menu and Context Screen designs Task Ticket (Team 4)

### ISSUE THREAD

**Issue by MrMeatballs** [UQdeco2800/2021-studio-7#46]
## Description
**Task**: Screens
**Feature Ticket**: #42 

Design and implement new screens for the Main Menu and the Context Screen. The Main Menu will have a screen before it called title screen, which wont have any button and prompt the user to press any key, reminiscent of arcades inserting a coin.  

## Dependencies
- N/A

## Milestones
- [x] Create empty screens for context and title screen.
- [x] Implement changing screens upon pressing buttons.
- [x] Put assets and text in for title screen.
- [x] Put assets and text in for context screen.
- [x] User testing 
- [x] Unit testing 

## Documentation
To be filled

## Members
- Krisna Bou @MrMeatballs 
- Michelle Kwok @MishKwok 
- Yue Zhang @yuezhang7

**Comment by MrMeatballs** [comment]
Temp screens for context and title screen, with buttons for switching between. Also the default first screen has been changed

**Comment by MrMeatballs** [comment]
Originally we had placed a png image for the title screen and would have the user click or press a button to progress to the main menu. Since there wasn't functionality for the title screen, it was not necessary to build assets for it. However a design choice of a flashing label would prove complex to have with it overlapping the png. As such, building the title screen with actual assets was done and added as a milestone
