### ISSUE TITLE
Audio design

### ISSUE THREAD

**Issue by YichuanChen** [UQdeco2800/2021-studio-7#47]
**Description**
Design the different audio when different gaming status.
**Feature:** 

--------------------------------------
**Milestones:** 
We are going to work on the:
 - [ ] Game Won audio
 - [ ] Game Lose audio
 - [ ] Game_pause audio
 - [ ] Click_audio

--------------------------------------
**Documentation**
N/A
--------------------------------------
**Member**
 - HAO LIANG(@s4594749 )
 - Yichuan Chen(@YichuanChen )

**Comment by s4594749** [comment]
![3121631624028_ pic_hd](https://user-images.githubusercontent.com/88121884/133541667-61da3940-10f0-45e9-ac2b-7078ffbfd552.jpg)
![3131631624029_ pic_hd](https://user-images.githubusercontent.com/88121884/133541677-896e1de1-f412-4f7e-9afb-ed05618684f8.jpg)
![3141631624031_ pic_hd](https://user-images.githubusercontent.com/88121884/133541681-873ef19e-1e55-4390-a7f5-e514ab45b2eb.jpg)
