### ISSUE TITLE
Interactable Objects and Associated Effects (Team 2)

### ISSUE THREAD

**Issue by tweeeb** [UQdeco2800/2021-studio-7#5]
# **Description**
**Task**: Interactable Objects
**Feature**: Make game objects interactable such that they can be used to achieve the game objective.

Feature will allow game objects to be interacted with. Interacting with objects will allow the player to progress/navigate throughout the map and complete the game. Players will need to 'interact' with a bed object to complete the win condition, and similarly with doors and furniture to progress through rooms, completing objectives. Interacting with objects may also alter a players stats (i.e. consuming an energy drink will increase player speed).

Animations will be created and added to interactable objects to indicate that they are interactive, as well as to indicate that they have been interacted with (e.g. A door opening). 
 
## **Basic Objects**
- **bed**:  Interact with this object to win the game.
- **door**:  Interact with this object to move to the next map.
 
## **Examples**
- **Interactable Component**:  Game objects can inherit the component class to make them interactable. 

# **Dependencies**
- A win/ lose condition for goal 4, dependent on team 5 (#7)
- A map for which objects are decided and implemented on to interact with for goal 2, dependent on team 3 (#6 )
 
# **Milestones**
- [x] Goal 1 (Aug. 25): Implement a single interactable object
- [x] Goal 3 (Aug. 28): Create more advanced animations for the interactable components, to indicate that they are interactable 
- [x] Goal 2 (Aug. 31): Expand upon the interactable component to allow for any future game object to easily become interactable
- [x] Goal 4: (Sep. 2) Implement functions to be called on objects
(yellow outline), and possibly an animation that plays once interacted (e.g. A door opening).
- [x] Stretch Goal: Expand upon the interactions class to allow for it to affect other features, such as player stats, enemy AI, timer, as well as to trigger the end of the game (interacting with the bed). Edit: Create a task based system i.e. complete tasks such as switching off the tv and feeding the cat to complete the level and avoid getting detected.

**Completion Deadline:** September 2nd

# **Tasks**
- [x] #10 
- [x] #13 

**Completion Deadline:** August 25th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/Interaction-with-objects)
- [Basic Interactable Objects Design](https://github.com/UQdeco2800/2021-studio-7/wiki/Basic-Interactable-Objects-Design) 
- [Basic Interactable Objects User Testing](https://github.com/UQdeco2800/2021-studio-7/wiki/Basic-Interactable-Objects-User-Testing)
 
# **Members**
- Treffery (@tweeeb )
- Ben (@benjackson45 )
- Jiarui (@Jrui24 )
- Junxiang (@Noctisw )
- Pranay (@pranaypremdas )

**Comment by uqnjain** [comment]
I would like you to add detail to your ticket. What object interactions will you enable? What about interactions that impact Player stats? What does goal 4 address? Additionally, dependencies usually include the teams (in your studio) you depend on to deliver your feature. You will need to list them under the dependencies field. Deadlines given in the template ticket were not strict, so feel free to arrange them as you see appropriate.

**Comment by ChanghaoXi** [comment]
Hello, fellas from Team 2! This is Raymond from Team 1. Could you please update your wiki page with sprites of interactable objects, so we can update the colour scheme of the main characters accordingly. Thanks :)

**Comment by Jantoom** [comment]
Hey from Team 5. You can trigger the interactive win/lose conditions using our events in `MainGameActions`. How to reference those events is found [here](https://github.com/UQdeco2800/2021-studio-7/wiki/Game-Transition-Loop#changes-to-maingameactions).

**Comment by tweeeb** [comment]
> 
> 
> Hey from Team 5. You can trigger the interactive win/lose conditions using our events in `MainGameActions`. How to reference those events is found [here](https://github.com/UQdeco2800/2021-studio-7/wiki/Game-Transition-Loop#changes-to-maingameactions).

Hey! Thanks for pushing to main, I wanted to ask where you guys have added the simulated end condition buttons? I'm having trouble triggering the win condition.

**Comment by ChanghaoXi** [comment]
Hello guys! This is Raymond from Team 1.  The wiki page for character design & sprites creation has been finalised eventually, with detailed information regarding the design process & justifications to decisions made. You are very welcome to have a look, the link to access it can be found in our feature ticket, as well as several individual tickets that are related to character design & sprite making. Good luck for sprint 1 :)
