### ISSUE TITLE
Door and TV interaction (Sep. 15)

### ISSUE THREAD

**Issue by tweeeb** [UQdeco2800/2021-studio-7#50]
# **Description**
**Task**: Implement door and TV interactions
**Feature**: Interactable Objects

In this feature, door interaction will be implemented. When interacted with (E key is pressed), the door will lead to the next room.   Checkout Main description of feature below to look at visual description of what this looks like. A TV interaction will also be made. In this interaction the player switches the TV off. This interaction was implemented with that idea that as the player is going through each level additional tasks that can give the player additional points will be given to the player. Switching off the TV will give the player additional points.

# **Milestones**
- [x]  Implement door animation (when E key is pressed it animates to a open door)
- [x]  Implement TV interaction (when E key is pressed it animates to a TV that is switched off)
# **Stretch Goals**
- [ ] Integrate door in walls
 
**Completion Deadline:** Sep 14th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/Object-Interaction)
 
# **Members**
- Pranay (@pranaypremdas )
