### ISSUE TITLE
Alternative Interaction System

### ISSUE THREAD

**Issue by Jantoom** [UQdeco2800/2021-studio-7#53]
# Description
 
The interaction system needs to be standardised to account for future entities that will use the system. As a result, the way interactions work must be revamped, without removing the merits of the first version.

Entities that must be interacted with will extend the new `InteractionComponent`. This component implements the `Interactable` interface that specifies all new methods relevant to interaction.

Collisions are listened to by the `PhysicsContactListener`, which will trigger **"collision_start"** and **"collision_end"** to the relevant entities.

Interactions will be triggered by a new `SurveyorComponent`. Its purpose is to instantaneously query the closest, valid collision and trigger the entity's **"interaction"** event. The component is activated when the player presses the E key, and de-activated when the player lets go of it. It should account for prolonged presses for future interactions that may require persistence.
 
## Example
- **Bed**: Feature-wise, this implementation will appear equivalent to the Interaction system used in Sprint 1. The differences will be completely under-the-hood.
 
# Dependencies
- Agreement on implementation from @tweeeb @benjackson45 @pranaypremdas 
 
# Milestones
- [x] Draft new interaction system (Sep. 4)
- [x] Create interface `Interactable` and implement it in `InteractionComponent` (Sep. 7)
- [x] Remake bed and mum collision functionality in components `BedActions` and `MumActions` (Sep. 7)
- [x] Create `SurveyorComponent` class using a physics raycast implementation  (Sep. 8)
- [x] Fix the `PlayerFactory`, `ObstacleFactory` and `NPCFactory` to use new components over the old ones (Sep. 9)
- [x] Clean up code, add beneficial physics, service locator, screen, game area and game functionality (Sep. 9)
- [x] Collaborate with other studio members to reach consensus on interaction standardisation (Sep. 10)
- [x] Rewrite Interaction documentation (Sep. 11)
- [x] Rewrite Interaction unit testing (Sep. 13)

**Completion Deadline:** Sep. 17
  
# Documentation
- [The Interaction System](https://github.com/UQdeco2800/2021-studio-7/wiki/Interaction-System)
- [Styling Guide and Best Practices](https://github.com/UQdeco2800/2021-studio-7/wiki/Styling-Guide-and-Best-Practices-for-Studio-7)
 
# Members
- Jaleel Abdur-Raheem (@Jantoom) (Jaleel Abdur-Raheem)

**Comment by Jantoom** [comment]
Documentation still needs UML diagrams, but it is otherwise complete with new information.
