### ISSUE TITLE
Leader Board and scoring

### ISSUE THREAD

**Issue by benisrael29** [UQdeco2800/2021-studio-7#58]
**Task:** Add a new button to the main menu which opens another screen. New screen will have a representation of the leader board which is a sorted array (username : score) stored in a text file after every play of the game. How the score is calculated will be posted to the wiki on completion. 

### Milestones

- [x] Implement Score tracking
- [x] Create leaderboard screen
- [x] Add design elements
