### ISSUE TITLE
Map Design with Map Objects (Team 3)

### ISSUE THREAD

**Issue by E-Roderick** [UQdeco2800/2021-studio-7#6]
## Description

Map design will include the assets and style for the map, as well as the underlying code (interfaces and classes) that will facilitate future map design (Map format?). As the maps are manually designed, there will be at least one designed map for workable gameplay.

The assets and style of the map will follow the theme of the game - Retro and Retrowave. Additionally, as the game is set inside of a house, the map will consist of rooms with “household” themes, while holding with the retro style. Objects that require interaction will also be made with these themes in mind, with additional care for recognisability.

We intend on separating components of the map into a series of classes and interfaces to facilitate future integrations. The current thinking is an overarching `map` class that will contain all information for each level. These `map` classes will contain a set of `room` classes, and these `room` classes will have the details pertaining to player interaction. Rooms will be bounded with `walls` that limit player movement, and contain the entities of interaction for a player, as well as `doors` that can lead between rooms.

## Dependencies

- Interactions with objects on the map: Team 2 (#5):
    - We will have to collaborate with this team to create the objects and they will add player interactivity with these objects.
- Isometric map display: Team 4 (#8):
    - We will need to ensure that the map generation and textures work with an isometric view/coordinate system.

## Documentation

- [Map Generation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Generation)
- [Border Generation](https://github.com/UQdeco2800/2021-studio-7/wiki/Border-Generation)
- Map and Object Assets

## Milestones

- [ ] Borders/boundaries task - Date: 31/8
- [x] Object design (Door, Bed etc.) - Date: 22/8
- [x] Wall Tile and Floor Tile Design - Date: 22/8
- [x] Room creation - Date: 1/9
- [x] Room/map design - Date: 1/9

## Members
- Luke Cronin (@Luke-Cronin)
- June Lee (@junelee045)
- Ethan Roderick (@E-Roderick)
- Yongzhi Zhou (@45229848)	
- Yichuan Chen (@YichuanChen)

**Comment by uqnjain** [comment]
The ticket looks good. Please create a documentation link for your feature and add it to your ticket. I look forward to reading it!

**Comment by E-Roderick** [comment]
Missed deadline for room creation due to other course work loads and a new dependence on isometric view. Updating deadline date to 24/08.

**Comment by E-Roderick** [comment]
Updating deadlines regarding map generation and design to reflect work pushed back due to dependencies and time commitments. From 24/08 to 01/09.

**Comment by junelee045** [comment]
Updated the deadline for the borders/boundaries milestone due to other commitments resulting in delaying the task from the 22/8 to the 31/8.

**Comment by E-Roderick** [comment]
Removed 'Room Switching' milestone because of time constraints, and uncertainty over implementation.

**Comment by ChanghaoXi** [comment]
Hello guys! This is Raymond from Team 1.  The wiki page for character design & sprites creation has been finalised eventually, with detailed information regarding the design process & justifications to decisions made. You are very welcome to have a look, the link to access it can be found in our feature ticket, as well as several individual tickets that are related to character design & sprites making. Good luck for sprint 1 :)

**Comment by Luke-Cronin** [comment]
Borders of the game rooms/level were not able to be translated into isometric view from the starting orthogonal frame. This major feature will be moved to a future Sprint.
