### ISSUE TITLE
Fix timer bug and Upgrade timer (Team 5)

### ISSUE THREAD

**Issue by XUEHUANG521** [UQdeco2800/2021-studio-7#62]
## Description
**Task**: fix timer bug and upgrade timer
**Feature**: #40 

Fix timer bug which can't trigger time lose condition and quit the game accidentally.
in addition,  work with designers to design animation for the timer and change timer display based on suggestion from Copy of Features "List of features for Sprint 2
" section. 

## Dependencies
- N/A

## Milestones
- [ ] Fix timer bug (10/09/2021).
- [ ] upgrade timer display (12/09/2021).
- [ ] implement timer animation (17/09/2021).

## Documentation
[Game Transition Loop](https://github.com/UQdeco2800/2021-studio-7/wiki/Pausing-and-Resuming)

## Members
- XUE HUANG(@XUEHUANG521 )

**Comment by pranaypremdas** [comment]
Hi, not sure if this is a timer issue or not, but it seems to be that the interactions don't work when there are less than 5 seconds left.

**Comment by XUEHUANG521** [comment]
> Hi, not sure if this is a timer issue or not, but it seems to be that the interactions don't work when there are less than 5 seconds left.
What do you mean?

**Comment by pranaypremdas** [comment]
> > Hi, not sure if this is a timer issue or not, but it seems to be that the interactions don't work when there are less than 5 seconds left.
> > What do you mean?

Well I think that there might be an issue with the timer interfering with the interactions. I could be wrong. But I have done the testing multiple times. It seems to be that after 5 seconds I can't interact with the TV or Door that I have created. So if there is anything that you think could be affecting it let me know. I am currently working on fixing it so if you think it is not an issue with the timer then don't worry.

**Comment by XUEHUANG521** [comment]
> > > Hi, not sure if this is a timer issue or not, but it seems to be that the interactions don't work when there are less than 5 seconds left.
> > > What do you mean?
> 
> Well I think that there might be an issue with the timer interfering with the interactions. I could be wrong. But I have done the testing multiple times. It seems to be that after 5 seconds I can't interact with the TV or Door that I have created. So if there is anything that you think could be affecting it let me know. I am currently working on fixing it so if you think it is not an issue with the timer then don't worry.

Actually, i have upgrade the timer based on feedback, which it would be more realistic, timer would start at 8 pm to 2 am. when time reach to 2 am, it would trigger the lose condition, as I still need half of day to modify this,  i didn't push it to the branch yet. it would be there tomorrow morning.

**Comment by XUEHUANG521** [comment]
Bug fixed
