### ISSUE TITLE
Reworked and Extended Map Generation

### ISSUE THREAD

**Issue by E-Roderick** [UQdeco2800/2021-studio-7#63]
## Description

**Task**: Reworked and Extended Map Generation

**Feature**: [Map Generation Extended](#36)

This task involves working on the loading and parsing of `drm` files to construct and generate maps. The use of `drm` files will be extended to work with the random tiling of predefined 'rooms', and will also include the ability to generate entities within the map.

The work will focus on restructuring the `drm` file format to properly handle the new, desired scope; simplifying the code that interacts with `drm` files; and, removing and fixing issues that persisted from Sprint 1.

## Milestones
- [x] Finalisation of extended `drm` syntax.
- [x] Loading and parsing of new `drm` syntax.
- [x] Unified map controller from individually generated rooms.
- [x] Entity placement spawning.

## Documentation
- [Map Generation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Generation)

## Members
- @E-Roderick 
- @Jantoom

**Comment by E-Roderick** [comment]
All tasks completed. Additional work may be to get working chaining of rooms.

**Comment by E-Roderick** [comment]
@Jantoom Possible note for future work, can the drm file handle atlases for animated entities?

**Comment by Jantoom** [comment]
I think that it can be extended to do that. For now that won't work because files are assumed to use the Texture class. Eventually, we will want beds and players to be fully customisable in drm files so that there is no need to have a String of textures in the game area class.
