### ISSUE TITLE
User testing plan for characters and NPCs (Team 1)

### ISSUE THREAD

**Issue by ChanghaoXi** [UQdeco2800/2021-studio-7#64]
# **Description**
**Task:** Create a standardised user testing plan that can be repeatedly used for gathering feedback for future iterative refinement of characters' and NPCs' sprites.
**Feature:** Character Design

Because the iterative design process is applied for sprites of characters and NPCs, multiple rounds of user testing evaluations will be required. Additionally, user testing was conducted without a standardised plan in the previous sprint, which caused impacts on reliability of the data gathered. Therefore, it is significant and necessary to have a standardised user testing plan as the basic guidelines for future evaluations. The following aspects are covered in the testing plan:

- Aims & objectives.
- Requirements of the organiser and participants.
- Materials required for a user testing session.
- Step-by-step guidelines for conducting an evaluation session.

**Please check the wiki pages under the documentation section below for more details, thank you!**

# **Milestones**
- [x] Document aims & objectives for the user testing plan. (Sept. 15)
- [x] Document requirements of the organiser and participants for the user testing plan. (Sept. 15)
- [x] Document materials that need to be prepared in advance for a user testing session. (Sept. 15)
- [x] Document step-by-step guidelines for conducting an evaluation session. (Sept. 15)

# **Dependencies**  .
- #57 .

# **Documentation**
- [Characters & NPCs Design User Testing](../..//2021-studio-7/wiki/Characters-&-NPCs-Design-User-Testing)

# **Members**
**Changhao Xi** (@ChanghaoXi) (Raymond)

**Comment by ChanghaoXi** [comment]
Task ticket created and reviewed

**Comment by ChanghaoXi** [comment]
Task ticket finalised and reviewed
