### ISSUE TITLE
New Male Character

### ISSUE THREAD

**Issue by shiyiling1** [UQdeco2800/2021-studio-7#66]
**Task:** Design and create a set of sprites for the new male playable character and import them into the Retroactive game engine 
**Feature:** Character Design

-do some research for the 80s neon colours and the type of the pajamas
-use the pixel studio to design a demo for the male character
-ask other peers for the feedback of the male character. 
-create a male based on the feedback also add the highlight and shade
-create all the sprints in different direction

# **Milestones**
- [x] do the research (Sept. 12)
- [x] create a demo for the male character(Sept. 13)
- [x] ask feedback and adjuest based on the feedback(Sept. 14)
- [x] **Completion Deadline:** Sept. 15

# **Dependencies**
- #37 
- #21 

# **Documentation**
- [NPCs & Characters Design](../..//2021-studio-7/wiki/NPCs-&-Characters-Design)

**Comment by ChanghaoXi** [comment]
task ticket reviewed and closed
