### ISSUE TITLE
Leaderboard Title Design

### ISSUE THREAD

**Issue by shiyiling1** [UQdeco2800/2021-studio-7#67]
**Task:** Create texture atlas for the mom NPC and the player character and write the test for the 'PlayerAnimationController'.

**Feature:**  
-Use the pixel studio to design a  couple of leaderboard titles. 
-ask other peers for the suggestion
-Decide the font style
-use the color of the main screen title as a reference for drawing the leaderboard title

- [x] create the leaderboard title

# **Milestones**
- [x] design the font style for the title (Sept.09)
- [x] ask peer and decided the font style(Sept.10)
- [x] decide the colour and print it (Sept.11)
- [x] **Completion Deadline:** Sept. 11

### Dependencies
- #42

**Comment by ChanghaoXi** [comment]
Task ticket reviewed and closed
