### ISSUE TITLE
In-Game/Win/Lose Transitions for the Game Loop (Team 5)

### ISSUE THREAD

**Issue by XUEHUANG521** [UQdeco2800/2021-studio-7#7]
# Description
**Task**: Implement win/lose transitions for the Game Loop
**Feature**: Win/Lose Condition Screens & Event Dispatching, Gameplay Timer

Our issue’s main focuses are adding the win/lose transitions into the game loop. This includes designing;
-  the win condition screen (main objective is met, according to the game wiki);
-  the “caught” lose condition screen (player is caught by the enemy NPC);
-  the “time’s up” lose condition screen (player fails to complete the objective by midnight)
              -   the thematic choice of “losing by midnight” may be subject to change

To make use of these screens, we will implement event dispatchers that allow the player to transition from the “in-game” state of the game to one of the end condition states (and vice versa). When the game is in the “win” state, a win screen will be displayed and when in either “lose” state, the appropriate lose screen will be displayed.

The “time’s up” lose condition requires the “in-game” state to have a timer tracking the time left for the player to complete the objective. Therefore, a timer will be implemented that will move closer to midnight, which will trigger a “lose” state if midnight is reached. 

We will implement a rudimentary mechanism from the “win” & “lose” states to go back to the “in-game” state, hence tying the Game Loop.

# Dependencies
Interactions between the player and objects that may trigger a win or lose scenario
1. Our win condition requires interaction with the bed
2. Our “caught” lose condition requires interaction with the enemy NPC

We will collaborate with Team 2 so that their components may trigger our dispatchers

# Milestones
- [x] Goal 1 (Aug. 19): Deliver two unique win/lose & timer design prototypes
- [x] Goal 2 (Aug. 20): Evaluate and decide on most suitable initial designs
- [x] Goal 3 (Aug. 26): Create event dispatchers to facilitate changing the game state
- [x] Goal 4 (Aug. 27): Implement the chosen screen design into the game
- [x] Goal 5 (Aug. 30): Coordinate event dispatching with Team 2 (#5)

**Completion Deadline:**  Aug. 31

# Documentation
More information on the how the screens are integrated can be found [here](https://github.com/UQdeco2800/2021-studio-7/wiki/Game-Transition-Loop).

# Changes to original feature
- Decided to combine win and lose screens and relevant components into 'EndGameScreen', 'EndGameActions', and 'EndGameDisplay' to simplify code. The consequences of this are that the win result must be passed to the `EndGameScreen` constructor and screen textures are dependent. This cascades to `EndGameDisplay` when creating the relevant `UIComponent`s. (@Jantoom)

# Members
- Hao Liang (@s4594749) (Hao Liang)
- Ruiqing Li (@richardrq) (Ruiqing Li)
- Xue Huang (@XUEHUANG521) (Xue huang)
- Roy Browning (@rbrowning66) (Roy Browning)
- Jaleel Abdur-Raheem (@jantoom) (Jaleel Abdur-Raheem)

**Comment by uqnjain** [comment]
The ticket looks good. Please create a documentation link (wiki) for your feature and add it to your ticket here. I look forward to reading it!

**Comment by ChanghaoXi** [comment]
Hello, fellas from team 5, this is Raymond from Team1, I have finalised the design of male characters with shades and other details, a copy of sprites has been uploaded to the discord channel of your team, pls feel free to use those sprites for winning/losing screen. Thanks :)

**Comment by tinagoyal203** [comment]
Hiii! team 5,  Tina from Team 1 here, I have completed the design of female character and the mom character as well and I have posted the google drive link for the sam on discord channels as well, feel free to use those sprites for winning/losing screen. cheers!

**Comment by XUEHUANG521** [comment]
> Hiii! team 5, Tina from Team 1 here, I have completed the design of female character and the mom character as well and I have posted the google drive link for the same on discord channels as well, feel free to use those sprites for winning/losing screen. cheers!

**Comment by ChanghaoXi** [comment]
Hello guys! This is Raymond from Team 1.  The wiki page for character design & sprites creation has been finalised eventually, with detailed information regarding the design process & justifications to decisions made. You are very welcome to have a look, the link to access it can be found in our feature ticket, as well as several individual tickets that are related to character design & sprites making. Good luck for sprint 1 :)
