### ISSUE TITLE
UML diagram and Junit test

### ISSUE THREAD

**Issue by wenqi6** [UQdeco2800/2021-studio-7#71]
**Task:** Create LeaderBoardDisplayTest, LeaderBoardScreenTest, MainGameScoreDisplayTest and ScoreComponentTest. Draw class diagram and sequence diagram.

# **Milestones**
- [x] Draw class diagram (Sept. 13)
- [x] Draw sequence diagram (Sept. 14)
- [x] Create test (Sept. 15)

# **Dependencies**
- #37 
- #21 

# **Documentation**
- [NPCs & Characters Design](../..//2021-studio-7/wiki/NPCs-&-Characters-Design)

**Comment by wenqi6** [comment]
![Class diagram drawio](https://user-images.githubusercontent.com/88083765/133530848-037411ae-e3ef-4656-9332-b1e428286ad9.png)

**Comment by wenqi6** [comment]
![MainGameScoreDisplay_draw](https://user-images.githubusercontent.com/88083765/133531238-39abaeea-3335-4128-87b1-3a876239216b.png)
![MainGameScoreDisplay_getscore](https://user-images.githubusercontent.com/88083765/133531240-00363526-eb0c-4e82-abeb-cdbb9c9a131c.png)
![MainGameScoreDisplay_new](https://user-images.githubusercontent.com/88083765/133531241-a9bf75f6-363b-4813-a5f5-7196fd9f250d.png)
![MainGameScoreDisplay_tick](https://user-images.githubusercontent.com/88083765/133531243-a9e1132a-1289-4080-93e3-35c7701a4821.png)
![MainGameScoreDisplay_updatePlayerHealthUI](https://user-images.githubusercontent.com/88083765/133531245-70070886-fe9c-4c60-986d-8dfc7be209d6.png)
![MainMenuActions_onLeaderboard](https://user-images.githubusercontent.com/88083765/133531246-2ab23044-78af-42a0-8cec-dacdd9fa0f14.png)
![ScoreComponent_changeScore](https://user-images.githubusercontent.com/88083765/133531248-51c14029-657e-4f4f-abbc-9742b02d04e1.png)
![ScoreComponent_create](https://user-images.githubusercontent.com/88083765/133531252-0f99e603-929d-4fb9-b73f-4b1a666c295d.png)
![ScoreComponent_getScore](https://user-images.githubusercontent.com/88083765/133531255-9548f300-05c8-438d-9598-ff94ad49c08e.png)
![ScoreComponent_new](https://user-images.githubusercontent.com/88083765/133531256-b56f40b6-b3d8-4932-9ab0-76a4e5ed0dad.png)
![ScoreComponent_tickScore](https://user-images.githubusercontent.com/88083765/133531257-d704fe02-2e67-4f23-a0a0-a1b75b7ddfcb.png)
![ScoreComponent_writeScoreToLeaderBoard](https://user-images.githubusercontent.com/88083765/133531258-c7a4bd24-b5ac-497a-9297-d943354e4424.png)
![LeaderBoardDisplay_addActors](https://user-images.githubusercontent.com/88083765/133531259-f611242f-f8b5-45c6-882d-b3cf41c57a03.png)
![LeaderBoardDisplay_create](https://user-images.githubusercontent.com/88083765/133531260-b8bc8c2d-9b1b-40ce-bc34-13b70fe6a62c.png)
![LeaderBoardDisplay_dispose](https://user-images.githubusercontent.com/88083765/133531262-f130d652-a302-406e-9fe8-609eba9306fe.png)
![LeaderBoardDisplay_draw](https://user-images.githubusercontent.com/88083765/133531264-93617a4a-70db-40c5-a226-53180582ab91.png)
![LeaderBoardDisplay_exitMenu](https://user-images.githubusercontent.com/88083765/133531265-77a3c277-506e-4b15-9c44-c25a2e2adb27.png)
![LeaderBoardDisplay_makeLeaderBoardTable](https://user-images.githubusercontent.com/88083765/133531266-109691e7-9972-4a4f-9e46-15b5b90b5534.png)
![LeaderBoardDisplay_makeMenuBtns](https://user-images.githubusercontent.com/88083765/133531268-5e763e5b-b2dc-4501-8436-abb1cd3a2140.png)
![LeaderBoardDisplay_new](https://user-images.githubusercontent.com/88083765/133531270-0436f727-aaf8-4b87-adc7-18fe7f09123d.png)
![LeaderBoardDisplay_update](https://user-images.githubusercontent.com/88083765/133531272-dd6860db-fe05-481e-a894-1c2da0921d1c.png)
![LeaderBoardScreen_new](https://user-images.githubusercontent.com/88083765/133531273-1ab0e20b-0b29-4004-8669-abc666dc4c2c.png)
![MainGameScoreDisplay_addActors](https://user-images.githubusercontent.com/88083765/133531281-756f68a4-06c9-4e73-aa06-711d9b41f121.png)
![MainGameScoreDisplay_countDown](https://user-images.githubusercontent.com/88083765/133531283-3d3c9e63-e82d-4792-a312-cfb3894b3194.png)
![MainGameScoreDisplay_create](https://user-images.githubusercontent.com/88083765/133531284-7f7aac19-9508-47ea-8f57-9c514d123a59.png)
![MainGameScoreDisplay_dispose](https://user-images.githubusercontent.com/88083765/133531286-3de9e1d6-cfce-4428-92a5-6c29c1473bd0.png)

**Comment by wenqi6** [comment]
![ForsetGameArea](https://user-images.githubusercontent.com/88083765/133551931-fcdf84fa-0e4f-4f1a-ba25-2a76e6e47605.png)
![GdxGame](https://user-images.githubusercontent.com/88083765/133551936-00136a7d-a050-432b-ae04-65e41d374e75.png)
![LeaderBoardDisplay](https://user-images.githubusercontent.com/88083765/133551938-f6c16264-dcca-4ecf-a116-8b97e4f87044.png)
![LeaderBoardScreen](https://user-images.githubusercontent.com/88083765/133551939-cb8ead99-500f-47b8-b1fb-aebfecbacb57.png)
![MainGameTimerDisplay](https://user-images.githubusercontent.com/88083765/133551941-9ac4babc-0b79-47e9-9af7-3e1f947de70b.png)
![MainMenuDisplay](https://user-images.githubusercontent.com/88083765/133551944-4da12fe2-d8a4-4a59-b569-79f37483e26c.png)
![MumAnimationController](https://user-images.githubusercontent.com/88083765/133551947-85987ee1-00f2-4e4c-a03e-f48b1998cb3c.png)
![Mumconfig](https://user-images.githubusercontent.com/88083765/133551949-190e19f9-0571-4b1a-b765-13af417c00cc.png)
![NPCConfig](https://user-images.githubusercontent.com/88083765/133551952-e59c3f4e-446d-4d60-846f-02d4243500bd.png)
![PhysicsMovementComponent](https://user-images.githubusercontent.com/88083765/133551954-23a441e8-e1c4-4506-9694-755515d898e2.png)
![PlayerAnimationController](https://user-images.githubusercontent.com/88083765/133551956-7d8ff41e-28f6-4a33-9a58-3e9c557cb93d.png)
![PlayerFactory](https://user-images.githubusercontent.com/88083765/133551960-4c9cf551-1cea-4e35-9444-68aa8a218bb6.png)
![SettingsMenuDisplay](https://user-images.githubusercontent.com/88083765/133551961-699b1a59-776e-471e-9056-bb9640f0d4d1.png)

**Comment by ChanghaoXi** [comment]
Task ticket reviewed and closed

**Comment by wenqi6** [comment]
![Class diagram drawio](https://user-images.githubusercontent.com/88083765/134458230-e7034afb-82e6-468b-aa97-c5358091b2a5.png)
