### ISSUE TITLE
Finalise Designs of Basic Interactable Objects

### ISSUE THREAD

**Issue by Jrui24** [UQdeco2800/2021-studio-7#75]
# **Description**
**Task**: Redesign basic interactable objects based on the feedback collected from Basic Interactable Objects User Testing.

**Feature**: Interactable Objects

Analyse several potential improvements that were provided in the Basic Interactable Objects User Testing. Trying to improve the design according to the feedback, also change the direction of the objects. Additionally, Communicate with Team 1 to ensure the door fit the character well.

# **Milestones**
- [x] Redesign the door and bed (Sept. 8)
- [x] Resize basic intractable objects (Door, Bed, TV) (Sept. 12)
- [x] Create animations for TV and growing bubble (Sept. 13)
- [x] Build atlas files for animations (Sept. 14)

# **Dependencies**
- #56  .

# **Documentation**
- [Basic Interactable Objects User Testing](https://github.com/UQdeco2800/2021-studio-7/wiki/Basic-Interactable-Objects-User-Testing)
- [Basic Interactable Objects Design](https://github.com/UQdeco2800/2021-studio-7/wiki/Basic-Interactable-Objects-Design)

# **Members** 
- Jiarui Li (@Jrui24 )
- Junxiang Wang (@Noctisw)
