### ISSUE TITLE
User Testing Plan for Basic and Functional Interactable Objects

### ISSUE THREAD

**Issue by Jrui24** [UQdeco2800/2021-studio-7#77]
# **Description**
**Task:** Create a user testing plan for gathering feedback for updated basic interactable objects, new functional interactable objects and new UI component.

**Feature:** Interactable Objects

Since responses are collected and evaluated, several changes have been made. This user test will test on the finalised basic interactable objects and the buff and debuff objects etc. The testing plan will be included:
- Background
- Aims & Objectives
- Testing Plan
- Evaluations & Reflections

# **Milestones**
- [x] Introduce the background of this user test. (Sept. 15)
- [x] List out the aims and objectives of this testing session. (Sept. 15)
- [x] Construct the testing process and questions that will be asked during the session. (Sept. 15)
- [x] Collect responses and evaluate. (Sept. 16)

# **Dependencies**
- #75 
- #76 

# **Documentation**
- [Additional Interactable Objects User Testing](https://github.com/UQdeco2800/2021-studio-7/wiki/Additional-Interactable-Objects-User-Testing#feedback-from-user-1)

# **Members** 
- Jiarui Li (@Jrui24 )
- Junxiang Wang (@Noctisw)
