### ISSUE TITLE
Movement (WASD) - (Team 4)

### ISSUE THREAD

**Issue by 44818919** [UQdeco2800/2021-studio-7#8]
### Movement (WASD) - (Team 4)
This ticket will see through the plans for team 4 in developing the following features: Isometric view, camera tracking the player and lastly, stamina relative to the player’s speed. 

The isometric view is to give a preferable camera angle of the game to the player. This will change the current view of the game engine.

The camera is to move with the player, so the player is always in the centre of the screen. As the player moves through the map, the camera will stay centred on the player and the room will move around them.

The player’s stamina will give the option for the player to give a speed boost to their character to get through a level faster.

### Dependencies 
All dependencies already exist in 2021 DECO2800 game engine of studio 7.
Character direction sprites designed by Team 1. 
Isometric map design by Team 3

### Milestones

- [x] Stamina integration (Aug 23)
- [x] Isometric View (Aug 25)
- [x] Player movement in Isometric (Aug 28) 
- [x] Camera Angle (Aug 31)
- [x] Main Menu Background (Sep 2)
- [x] Unit Testing (Sep 2)

### Members
@MrMeatballs 
@MishKwok 
@AnsonCNS 
@44818919 
@yuezhang7

**Comment by uqnjain** [comment]
The ticket looks good. Dependencies include teams you depend on to deliver your feature. Please include the appropriate teams under that field.

**Comment by naziah28** [comment]
See https://github.com/UQdeco2800/2021-studio-7/wiki/Terrain  for a start on implementing an iso map

**Comment by MrMeatballs** [comment]
We added an extra milestone of designing a main menu screen as the default box boy name needed to be changed.

**Comment by ChanghaoXi** [comment]
Hello guys! This is Raymond from Team 1.  The wiki page for character design & sprites creation has been finalised eventually, with detailed information regarding the design process & justifications to decisions made. You are very welcome to have a look, the link to access it can be found in our feature ticket, as well as several individual tickets that are related to character design & sprites making. Good luck for sprint 1 :)
