### ISSUE TITLE
Game loop Improvement for player experience (Team 5)

### ISSUE THREAD

**Issue by XUEHUANG521** [UQdeco2800/2021-studio-7#86]
# **Description**
Task : Improve Game Loop implementation for user experience.
Feature: Pause Screen improvement, Collaborate with Team 4 for Design timer rule, design game sounds and collaborate with team 3 for random map generation.
Our issue’s main focuses in sprint 3 are Improve Game Loop implementation, which includes:
              - Improve Pause screen
              - Add sounds for events like click event, etc.
	  - Design and implement different rules in game 

#  **Dependencies**
Interactions between the player and objects that may trigger a win or lose scenario 
- Our win condition requires interaction with the bed
- Our “caught” lose condition requires interaction with the Mom NPC
- Our “time out” lose condition requires player can’t win the game until runtime per round ends
- We will collaborate with Team 2 so that their components may trigger our dispatchers
- We will collaborate with Team 3 so that game event audio design and random map design can be implemented on time
- We will collaborate with Team 4 so that timer rule in game would change depends on situation

# **Milestones**
- [x] Design Timer rule (Sept. 21)
- [x] Implement Timer Rules  (Sept. 25)
- [x] Add animation for Timer (Oct. 2)
- [x] Add event audio into game (Oct. 2)
- [x] Fully functional pausing and pause menu (Oct. 5)

Completion Deadline: Oct. 6

# **Members**
Hao Liang (@s4594749) (Hao Liang)
Xue Huang (@XUEHUANG521) (Xue huang)
Roy Browning (@rbrowning66) (Roy Browning)
Jaleel Abdur-Raheem (@jantoom) (Jaleel Abdur-Raheem)
