### ISSUE TITLE
Minimap, footstep sounds, main menu scroll and context screen clean up (Team 4)

### ISSUE THREAD

**Issue by MrMeatballs** [UQdeco2800/2021-studio-7#88]
## Description
This feature ticket will introduce a new feature of Minimap. The minimap will help give players the navigation they need between rooms as they may want to do side objective chores. 

Furthermore footsteps sound effects will be added so players can hear the mum getting closer. 

The main menu scrolling is a design feature to enhance the arcade aesthetic, as players will select the main menu buttons with the arrow keys. 

Further work in the context screen will have more instructions for the controls.

## Dependencies
Team 3 for the mini map generation 

## Documentation
to be filled

## Milestones
- [x] Add more context screen information
- [ ] Footstep sound effects for mum
- [x] Main menu scroll select
- [x] Minimap

## Members
* Nok Sang Chan (@AnsonCNS)
* Michelle Kwok (@MishKwok )
* Hayden Padget (@44818919 )
* Krisna Bou (@MrMeatballs )
* Yue Zhang (@yuezhang7 )
