### ISSUE TITLE
Interaction Overhaul 2: Electric Boogaloo

### ISSUE THREAD

**Issue by benjackson45** [UQdeco2800/2021-studio-7#89]
#**Description**
**Task**: Rework the interaction system again
**Feature**: [Implement all Interactable Components](https://github.com/UQdeco2800/2021-studio-7/issues/38)

Rework the way the interaction system is implemented.

# **Milestones**
- [x] Get E-key interaction to line up with object highlighting
- [x] Create removeEvent function
- [x] Fix multiple object bug (Interaction doesn't work when colliding with multiple objects)
- [x] Implement changes across all interactable objects
- [x] Rewrite unit tests
- [x] Create new UML diagram

**Completion Deadline:** Sep. 24

# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2021-studio-7/wiki/Object-Interaction)
- [Main description of functionality](https://github.com/UQdeco2800/2021-studio-7/wiki/Interaction-System)

# **Members**
- Ben Jackson (@benjackson45)
- Pranay Premdas (@pranaypremdas )
- Treffery Webb (@tweeeb)
- Jaleel (@Jantoom)
