### ISSUE TITLE
Pathfinding AI for Enemies and NPC's

### ISSUE THREAD

**Issue by tweeeb** [UQdeco2800/2021-studio-7#90]
# **Description**
**Task**:  Path finding
**Feature**: Implement pathfinding such that enemies and NPC's may navigate the map to reach a 'flagged' end point

Pathfinding will allow enemies and NPC's to generate paths from their location to a target location. In game, this will be used for the Mum NPC to route from her spawn location to the bed entity of the players bedroom (to check they are in bed). The path finder should then be able to use again to route to another location (e.g. the TV to check the player is not watching TV).

The path finder, when executing to move the enemy along the generated path, should be capable of being interrupted by the entity 'spotting' the player character through line of sight, and then implementing existing game functions to move towards the player. When the enemy loses line of sight, it will generate another path back to its original objective. 

As a stretch goal, path finding will also be implemented on sibling or pet NPC's who will generate an alert sound that will cause the Mum NPC to immediately reroute to the location of the noise.

This feature will greatly improve the difficulty of the game, suspenseful atmosphere, story depth and player experience.  

## **Basic Objects**
- **Path**:  A path for the entity to follow
 
## **Examples**
- 

# **Dependencies**
-  Wall implementation to navigate around (#36)
-  Obstacles to navigate around (#38)
- A  map to navigate a path along
 
# **Milestones**
- [] Add flags on obstacle object entities (e.g. bed, TV) that can be used as 'end flags' to navigate towards
- [] Implement A* path finding from a given map position to a 'end point'
- [] Implement a interrupt for path finding due to line-of-sight interaction with player entity and/or alert sounds that reroute enemy entity to location of alert sound effect
- [] Sequential A* navigation

**Completion Deadline:** October 8th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/)

# **Members**
- Treffery (@tweeeb )
- Benjamin (@benisrael29 )

**Comment by ChanghaoXi** [comment]
Hello, this is Raymond from Team 1, I just read through your description of the mechanism of pathfinding. So basically, the end spot of the generated path (target location) will be interactable objects like bed and TV, then in the process that mom is heading to the target location if the player is in her sight (within a certain radius), she will start to chase the player until the player is no longer visible in her sight, and at that point, she will continue to move towards the specified end spot of her path, is it correct? Thanks in advance for your clarification. @tweeeb

**Comment by tweeeb** [comment]
@ChanghaoXi yes! That's the intended functionality. Thank you for linking this in your team feature ticket as well.

**Comment by ChanghaoXi** [comment]
@tweeeb No worries at all! Thanks a lot for your clarifications to the pathfinding feature, I will update the feature ticket of Team 1 for a little bit to make the description of pathfinding there consistent with this one. Also, based on the plan of sprint 3, our head programmer @benisrael29 will mainly focus on implementing animations for isometric sprites and animations for switching characters before the mid-semester break and he will be able to work with you for the pathfinding function during the break. Please check out the feature ticket of Team 1 for more information and let me know if you have any question :)
