### ISSUE TITLE
Modify Object Spawns for Path-Finding and Proximity Testings for A* Implementation

### ISSUE THREAD

**Issue by tweeeb** [UQdeco2800/2021-studio-7#91]
# **Description**
**Task**: Modify Object Spawn
**Feature**: Path finding for Enemies and NPC's

Single-use items will be items that may be 'used' by the player entity in-game in order to modify player stats temporarily, and then the entity will be deleted from the game. For example, when a player interacts with a energy drink item, their base movement speed will be increased. This will factor into player strategies to win the game.

# **Milestones**
- [ ] Co-ordinates of spawn retrieved on game generation
- [ ] Co-ordinates accessible from new Path Finding class.
- [ ] Co-ordinates accessible from the enemy entity.
- [ ] Generate accurate proximity between object and enemy entity 
- [ ] Testing
 
**Completion Deadline:** Sep 14th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/)
 
# **Members**
- Treffery (@tweeeb )
