### ISSUE TITLE
Refine Intractable Objects Designs and Create Animations for Functional Interactable Objects

### ISSUE THREAD

**Issue by Jrui24** [UQdeco2800/2021-studio-7#92]
# **Description**
**Task:** Refine the door objects to make them more fitting to the wall. Evaluate the user testing responses (see Documentation), consider possible improvements and refine designs. Create animations and make atlas files for functional interactable objects. 

**Feature:** Interactable Objects

# **Milestones**
- [ ] Evaulate responses based on user testing (Sep. 24)
- [ ] Create animations for functional interactable objects. (Sep. 26)
- [ ] Finish atlas file for functional interactable objects. (Sep. 28)
- [ ] Refine interactable objects designs. (Sep.30)
- [ ] Find suitable sound effects for interactable objects. (Sep. 30)

# **Documentation**
- [Additional Interactable Objects User Testing](https://github.com/UQdeco2800/2021-studio-7/wiki/Additional-Interactable-Objects-User-Testing#feedback-from-user-1)

# **Members** 
- Jiarui Li (@Jrui24 )
- Junxiang Wang (@Noctisw)

**Comment by ChanghaoXi** [comment]
Hello designers from Team 2, This is Raymond from Team 1. Could you guys tell me your expected basic settings for scale (width x height) and pixel density of your latest version of interactable objects such as bed and TV? We are trying to iterate the design of character sprites to make them with a higher resolution via increase pixel density for a little bit. Thanks in advance:)

**Comment by Noctisw** [comment]
> @Jrui24 @Noctisw Hello designers from Team 2, This is Raymond from Team 1. Could you guys tell me your expected basic settings for scale (width x height) and pixel density of your latest version of interactable objects such as bed and TV? We are trying to iterate the design of character sprites to make them with a higher resolution via increase pixel density for a little bit. Thanks in advance:)

Yeah, when you are ready, just tell us the pixel grids.

**Comment by ChanghaoXi** [comment]
Hello, designers from Team 2! @Noctisw  @Jrui24 It is Raymond from Team 1 again. I'm currently making sprites for characters when they falling down because of the banana peel. We are planning to replace the original black outline with the red one to indicate that the character is getting a nagative impacts from the banana peel after contact with it. Just have one question about how does the banana peel work: Will it reduce the speed of the character within a certain period of time (opposite to the energy drink), or it will simply make the character fall down (this can be achieved via animations), but without additional negative impacts.Thank you in advance for your clarifications :)
