### ISSUE TITLE
Gameplay Improvements and Additional Adjustments (Team 3)

### ISSUE THREAD

**Issue by E-Roderick** [UQdeco2800/2021-studio-7#93]
## Description

This feature involves several possible tasks, focusing on the introduction of a large gameplay system.

Texture work will involve the creation and improvement of textures regarding obstacles. These obstacles will be entities that represent inanimate, house-hold objects like furniture.

The implemented gameplay system will be either the creation of a map destruction feature, the creation of a player-based obstacle system, or a checklist/objectives implementation. The map destruction will focus on the removal of wall entities based on player action. 

The player-based obstacle system would be a system to allow players to move certain obstacle entities around the map, providing users with the ability to impede enemy NPCs. This obstacle will be interactable with the player and can be picked up and removed from the map, then subsequently placed on command by the player. A texture for this interactable object will also be designed. The placing down of the box object will be based on the player direction they are facing (i.e. 1 in game tile in front of the player). 

The checklist/objective system would be the linking of entities with an player-accomplishable goal, with progress tracking to report completion to the player. User testing will be conducted to choose the work direction.

## Dependencies

- Interactable object for box interaction handling (#89)

## Documentation
[Map Destruction Documentation](https://github.com/UQdeco2800/2021-studio-7/wiki/Map-Destruction-Concept)

## Milestones

- [ ] Feature direction user testing completion.
- [ ] Random entity spawning.
- [ ] Create Box Texture
- [ ] Spawn interactable entity in map (i.e. box)
- [ ] Player interaction with box
- [ ] Delete entity from map on player interaction
- [ ] Player replace box entity in-game

## Members
- Luke Cronin (@Luke-Cronin)
- June Lee (@junelee045)
- Ethan Roderick (@E-Roderick)
- Yongzhi Zhou (@45229848)	
- Yichuan Chen (@YichuanChen)

**Comment by Luke-Cronin** [comment]
Updated and added information on pick-up and placing interactable object

**Comment by E-Roderick** [comment]
Removed references to other tasks to make feature more cohesive.

**Comment by Luke-Cronin** [comment]
Now that the mum has been removed from the game, we won't be working on any feature items related to mum NPC enemy pathfinding or destruction of walls. It will mainly be work relating to player interactions with object pickup and place

**Comment by junelee045** [comment]
Added documentation for concept of wall destruction. Given the mum entity removal, this feature possibly won't be implemented.
