### ISSUE TITLE
Completing Sprint 2 Animations and Implementing Fog effect 

### ISSUE THREAD

**Issue by pranaypremdas** [UQdeco2800/2021-studio-7#95]
In this feature, the TV animation will be changed to a dynamic animation that is constantly running until interacted with. In Sprint 2 the TV animation had a static animation where the frames of each "switched on" tv were displayed once for only 1 frame. In this sprint a dynamic animation where the change is noticeable will be implemented.

# **Milestones**
- [ ] Complete TV animations
- [ ] Add a fog animation
- [ ] Stretch goal - implement sound effects for each interaction with interactable objects.

**Completion Deadline:** September 27th

# **Documentation**
- [Main description of feature](../..//2021-studio-7/wiki/)

# **Members**
- Pranay (@pranaypremdas )
