### ISSUE TITLE
click_sounds effect and clock image for timer

### ISSUE THREAD

**Issue by s4594749** [UQdeco2800/2021-studio-7#97]
**sounds**

# **Milestones**
- [ ] Complete sounds effect
- [ ] Add timer image
- [ ] implement the sounds effect for each interaction

**Completion Deadline:** September 29th

**members**
hao liang(s4594749)
